### PR TITLE
Add Input::is_post()

### PR DESCRIPTION
**Pull request by Onuma0519**
Because the branch of the POST method is commonly used in the application.

### CODE REVIEW

**Comment by WanWizard** [comment]
What is the added benefit over `if (Input::method() == 'POST')` or `if (Input::post())` ?

For me this doesn't add anything, and while it may address your use case, you can easily argue why not an `is_get()`, which that is far more common?

**Comment by Onuma0519** [comment]
Input :: method() ,  using the Request class. 
I would like to complete in the Input class. 
Input :: post(),  if there are no parameters, it becomes false

**Comment by WanWizard** [comment]
The request class is the only reliable place for the current request method. Your solution isn't. 

If you don't care, you can always extend the Input class and add the method yourself. I can not be added to the framework, as it will not always return the correct request method.

**Comment by WanWizard** [comment]
Problem is that $_SERVER is global. If your main request (the one done by the browser) is a POST, $_SERVER will reflect that, and your is_post() will return true.

However, if your controller then does an HMVC request, that request is a GET (unless you make it a post). And is_post() will still return true, while Input::method() will return 'GET'.

This is what I mean by "not reliable".

**Pull request closed without merging**
