### PR TITLE
Fix Fuel::STAGE const name and value

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by WanWizard** [comment]
Question is if you call the environment 'staging', shouldn't the constant not also be called STAGING ?

It will possibly break BC, so we have to document this.

**Comment by kenjis** [comment]
If we can change it to `Fuel::STAGING`, I want to do.

**Comment by WanWizard** [comment]
Ok. I think it's more consistent. I'll update the documentation

**Comment by kenjis** [comment]
I'm sorry I forgot my sign. So I amended the commit with fixing the const name.

**Pull request merged**
