### PR TITLE
Update record on DB Session write

### PR DESCRIPTION
**Pull request by andrewwheal**
If you have a shutdown handler which wants to write to the session then you get problems with duplicate `session_id`s when using the DB session driver because the record was not being set and it was trying to create a duplicate session record in the DB

### CODE REVIEW

**Comment by frankdejonge** [comment]
@SicoAnimal is there a reason that you're not listening to the shotdown event provided by the Event class?

**Comment by andrewwheal** [comment]
We use this code `\Event::register('shutdown', array($this, 'save'));` is there a better way?

**Comment by WanWizard** [comment]
Why have a separate handler? All sessions are processed/updated via the shutdown event, that is already in place?

**Comment by andrewwheal** [comment]
We have a shutdown handler which saves a e-commerce basket to the DB and then adds the ID of the quote to the session so the we can retrieve it in the next request. We use a shutdown handler so that we can manipulate the quote where ever needed and know that it will always be saved at the end of the request.

We run the below code to set the required information to the session:

```
\Session::set("basket.{$this->_name}.quote_id", $this->quote()->id);
\Session::write();
```

The write was necessary because the session was already being written before our code.

UPDATE: everything worked fine when using the cookie driver

**Comment by WanWizard** [comment]
So the actual issue is about execution order? Do you autoload the session, or start it manually?

For this reason I've implemented reverse execution of shutdown events in the past, to make sure the event defined first is executed last, exactly to avoid the issue of the session being closed too early. 

It looks like this mechanism was removed somewhere when the event class was refactored, because I can't find that code anymore in the 1.7 codebase...

**Comment by WanWizard** [comment]
Correction: they are reversed, the logic for that has been moved to the instance, and controlled by the 4th parameter of trigger(). 

Perhaps you can check in which sequence they are executed, and also check when the session event is registered, and when you register your shutdown event...

**Comment by andrewwheal** [comment]
I put some logs in on our live site, so below is the order things are executed:

```
ERROR - 2013-09-03 11:10:36 --> whealer - Register Shutdown: Session
ERROR - 2013-09-03 11:10:36 --> whealer - Register Shutdown: Basket
ERROR - 2013-09-03 11:10:39 --> whealer - Fuel\Core\Session_Db::write
ERROR - 2013-09-03 11:10:39 --> whealer - PropShop\Core\Basket::save
ERROR - 2013-09-03 11:10:39 --> whealer - Fuel\Core\Session_Db::write
```

UPDATE: `Basket::save` is logged just before it calls `Session::write()`

**Comment by WanWizard** [comment]
And you autoload the session (always load)?

**Comment by andrewwheal** [comment]
Nope, session is not in the always load config

**Comment by WanWizard** [comment]
Ok, so it's caused by loading the session later then registering the other shutdown events, causing the frameworks' internal shutdown methods to be called after the ones you register in the code.

I'll have to think about it, perhaps we need an "app_finished" event you can hook into, instead of "shutdown".

**Pull request closed without merging**
