### PR TITLE
Add merge_assoc() method to Arr class

### PR DESCRIPTION
**Pull request by andrewwheal**
Force merge to not change integer keys that already exist

### CODE REVIEW

**Comment by it-can** [comment]
maybe add a test?

**Comment by andrewwheal** [comment]
I wanted to make sure it would get accepted before I put time into tests and documentation

**Comment by it-can** [comment]
oooh I see...

**Comment by WanWizard** [comment]
@FrenkyNet looks good to me, what do you think?

**Comment by it-can** [comment]
still missing a test?

**Comment by WanWizard** [comment]
I'm not finished yet... ;)

**Comment by WanWizard** [comment]
https://github.com/fuel/core/commit/a5b773250aecd57f7f7f484735d03b762939e528

**Pull request merged**
