### PR TITLE
Use '.' as directory separator in view file path

### PR DESCRIPTION
**Pull request by ronan-gloo**
Add Arr::get() like syntax support for view paths. Ie:

`View::forge('folder.subfolder.file')`

### CODE REVIEW

**Comment by WanWizard** [comment]
What's the point of using dots? Doesn't this do exactly the same?

```
View::forge('folder/subfolder/file')
```

**Comment by WanWizard** [comment]
It will also break the Parser package, as using

```
View::forge('folder.subfolder.file.tpl')
```

will be converted to "folder/subfolder/file/tpl", which causes the smarty or twig template not to be found.

**Comment by frankdejonge** [comment]
I think this was to mimic Laravel's view behaviour? And indeed not bc, adds unneeded/unwanted string processing, and Parser difficulties.

**Comment by ronan-gloo** [comment]
I didn't know about parser, so you're right WanWizard...

FrenkyNet:
Not especially, but i through that sharing same path logic for Lang, Config and View can be usefull if based on controller / action names detection.

**Pull request closed without merging**
