### PR TITLE
Change for parsing namespaced-xml

### PR DESCRIPTION
**Pull request by hackoh**
PR for https://github.com/fuel/core/issues/1442#issuecomment-26481677

### CODE REVIEW

**Comment by hackoh** [comment]
I will write this doc, ASAP.

**Comment by frankdejonge** [comment]
@hackoh could you more the vars above the forge function? We always have vars first, then methods.

**Comment by hackoh** [comment]
@FrenkyNet 

Really?

IIRC, static vars are put before static methods, and instance vars are put before instance methods. aren't they?

**Comment by WanWizard** [comment]
Order is:
class constants, static properties, static methods, instance properties, constructor, magic methods, public methods, protected methods (think I have all).

**Pull request merged**
