### PR TITLE
Apply chmod on every Config_File->save(), remove specific chmod on crypt config

### PR DESCRIPTION
**Pull request by felixgilles**
The specific `chmod` on the `crypt.php` config file is an issue: the name of the crypt config file is not necessarily `crypt.php`.

With moving the `chmod` in `Config_File->save()`, the `chmod` will be executed for crypt config file, but also for all others config files.

### CODE REVIEW

**Comment by WanWizard** [comment]
Good find!

**Comment by Savageman** [comment]
This introduced an E_Warning ([ Warning ]: chmod(): Operation not permitted) issue when saving a file we don't own.

Chmod is only allowed for the owner of a file. We could either check for posix_geteuid() == fileowner() or use the @ operator.
I'm not fan of the latter, but this is a native call so I think it's ok. But the first solution relies on the POSIX extension to be enabled (which should be by default but may also be disabled...).

**Comment by WanWizard** [comment]
Fixed.

**Comment by Savageman** [comment]
Thanks :)

**Pull request merged**
