### PR TITLE
Save raw SQL for profiler's use with EXPLAIN

### PR DESCRIPTION
**Pull request by jimcottrell**
Currently PHPQuickProfiler runs an EXPLAIN query for any saved SELECT queries, but it builds the EXPLAIN using the SQL that has already been escaped for output.  This is a simple patch to save the raw SQL and use that instead.

### CODE REVIEW

**Comment by WanWizard** [comment]
I believe the profiler shouldn't touch the profiling data, so it should not be escaped there. That should be the task of the display code in the profiler.

This fix will also store every query twice, which will increase the memory consumption of the application.

**Comment by jimcottrell** [comment]
I definitely agree with you that ideally the display code should be responsible for escaping the data.  I just went for the simplest possible change, figuring that the memory issue isn't that big of a deal because profiling is a development/testing activity, and not something for production anyway.

**Comment by jimcottrell** [comment]
I'd be happy to submit a slightly more involved pull request if you'd like.

**Comment by WanWizard** [comment]
Please do so, I don't have the time atm.

**Comment by jschreuder** [comment]
As this one won't go in I'm closing this pull-request, you can open a new one when you modified it as agreed upon.

**Pull request closed without merging**
