### PR TITLE
HTTP_ACCEPT is always checked to detect REST format by default

### PR DESCRIPTION
**Pull request by crynobone**
Config::get('rest.ignore_http_accept') by default is not set, which would return null, therefore the condition would return true and additional checking is require. We should add a default value to avoid overhead with the additional checking unless specifically requested

Signed-off-by: crynobone crynobone@gmail.com

### CODE REVIEW

**Comment by philsturgeon** [comment]
It should be set by default, which is probably a better problem to fix. 

Also, that condition would be better suited as === true instead of defaulting to true and !== false

**Comment by crynobone** [comment]
It was changed at f332919 from === false to !== false which cause the it to always run format detection via HTTP_ACCEPT

**Comment by philsturgeon** [comment]
Right now you are saying "if config is null, make it false, then check for false". Just check if its true or not instead of faffing.

**Comment by crynobone** [comment]
Updated based on suggestion, so the original code is right all along...

**Comment by philsturgeon** [comment]
Is it? Surely it should be `=== true`,  which is what I've been suggesting.

**Comment by crynobone** [comment]
The config description suggest 'ignore_http_accept', from my understanding of it

ignore_http_accept === true (shouldn't check HTTP_ACCEPT)
ignore_http_accept === false (HTTP_ACCEPT shouldn't be ignore, check it)

I might be wrong though.

**Comment by philsturgeon** [comment]
This has been fixed in 1.1/develop, thank you for pointing out the issue!

**Pull request closed without merging**
