### PR TITLE
Bugfix Image_Imagemagick->_watermark() and _rounded() functions

### PR DESCRIPTION
**Pull request by fastcgi**
Bugfix Image_Imagemagick->_watermark()   and _rounded()

### CODE REVIEW

**Comment by WanWizard** [comment]
This is a weird issue that I can't reproduce.

You're mentioning a bash error. On Linux, exec() directly calls the binary, it doesn't load the shell first. and "convert" is a binary, not some sort of script. So what is loading bash in your case, and why?

What is your exact server setup? OS, version, webserver, PHP version, ...

**Comment by fastcgi** [comment]
**the system version**

``` shell
fish@Fish-ubuntu:~$ uname -a
Linux Fish-ubuntu 3.5.0-31-generic #52~precise1-Ubuntu SMP Fri May 17 15:27:06 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
fish@Fish-ubuntu:~$ cat /etc/issue
Ubuntu 12.04.2 LTS \n \l
```

**ImageMagick version**

``` shell
fish@Fish-ubuntu:~$ convert -version
Version: ImageMagick 6.6.9-7 2012-08-17 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP 
```

**apache version**

``` shell
fish@Fish-ubuntu:~$ /usr/sbin/apache2 -v
Server version: Apache/2.2.22 (Ubuntu)
Server built:   Mar  8 2013 15:53:13

```

**php version**

``` shell
fish@Fish-ubuntu:~$ php -v
PHP 5.3.10-1ubuntu3.6 with Suhosin-Patch (cli) (built: Mar 11 2013 14:31:48) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with XCache v1.3.2, Copyright (c) 2005-2011, by mOo
    with Xdebug v2.1.0, Copyright (c) 2002-2010, by Derick Rethans
```

Do you used  ImageMagick drivers?

**Comment by WanWizard** [comment]
It's been a while, but I have never seen these issues.

My question however is not related to imagemagick at all, but about the fact that you have a bash error, but bash should not be invoked by an exec() call...

**Comment by fastcgi** [comment]
@WanWizard 

the details  in these reviews:

https://github.com/fuel/core/issues/1447

https://github.com/fuel/core/issues/1451

**Pull request merged**
