### PR TITLE
Fixes 'for' attribute in labels, closes #751

### LINKED ISSUE #751: Wrong label's "for" attribute
I'm using fieldset class (but I think this is a problem of Form class) ... and I notice that labels have a wrong "for" attribute, the auto_id_prefix is double.

<pre>
&lt;label for="form_form_code" class="control-label">Code&lt;/label>
&lt;input type="text" value="" name="code" id="form_code" required="required">
</pre>

### PR DESCRIPTION
**Pull request by sergiigrebeniuk**
Signed-off-by: delmot grebenjuk.s@gmail.com

### CODE REVIEW

**Comment by jschreuder** [comment]
Good job, but lacking consideration for 1 eventuality: when someone hasn't given an ID to the field and has auto_id switched off, in that case this would give an empty `for=""`. If you make this conditional on there being an actual ID I'll accept the pull-request (you don't have to make another request, just commit the fix to the same branch).

**Comment by sergiigrebeniuk** [comment]
Hi Jelmer, here you are

**Comment by kenjis** [comment]
@delmot your hack seems to miss prefix.

before your hack:

```
<label for="form_">
```

applied your hack:

```
<label for="gender">
```

**Comment by mikebranderhorst** [comment]
field.php line 391

```
$auto_id = str_replace(array('[', ']'), array('-', ''), $this->name);
$this->set_attribute('id', $auto_id);
```

to

```
$auto_id = $form->get_config('auto_id_prefix', 'form_');
$auto_id .= str_replace(array('[', ']'), array('_', ''), $this->name);
$this->set_attribute('id', $auto_id);
```

field.php line 478

```
$label = $this->label ? $form->label($this->label, $this->get_attribute('id', null)) : '';
```

to

```
$label = $this->label ? $form->label($this->label, $this->get_attribute('id', null), $this->get_attribute('id', null) ? array('for' => $this->get_attribute('id', null)) : array()) : '';
```

solves the problem

and I think `data[test]` must not be translated to `data-test` but `data_test`

**Comment by jschreuder** [comment]
Closed, will be handled by issue #839.

**Pull request closed without merging**
