### PR TITLE
Allow to get directory's files and iterate it

### PR DESCRIPTION
**Pull request by kusmierz**
Now you can easily get files (protected $content), iterate File_Handler_Directory as an array (it returns File_Handler_*), and use it as follows:

``` php
$dir = \File::instance('images');
$gallery = $dir->read_dir($path);
```

than in twig:

``` twig
{% for image in gallery %}
<img src="{{ url(image.get_url()) }}" />
{% endfor %}
```

### CODE REVIEW

**Comment by WanWizard** [comment]
@jschreuder any comments?

**Comment by frankdejonge** [comment]
Besides the coding style that needs to be fixed this seems like a nice addition to the class.

**Comment by kusmierz** [comment]
What's wrong with coding style?

**Comment by frankdejonge** [comment]
"||" should be "or", brackets should be on a new line. Things like that. For a full coding style guide you can take a look here: http://docs.fuelphp.com/general/coding_standards.html

**Comment by kusmierz** [comment]
Thanks, I'll check it.

**Comment by kusmierz** [comment]
By the way - in fact "or" and "||" aren't the same.

Try for example:

``` php
$a = false || true; // true
$b = false or true; // false
```

http://es.php.net/manual/en/language.operators.logical.php

**Comment by frankdejonge** [comment]
@kusmierz We are aware of this, and actually one of the reasons to just use one of them. Mixing the two will cause a lot of confusion. Always use them with care :)

**Comment by WanWizard** [comment]
@kusmierz any chance on an update? And also add this new functionality to the documentation please.

**Comment by kusmierz** [comment]
I'll update it, but later, probably in the weekend.

**Comment by WanWizard** [comment]
@kusmierz any update on this?

**Comment by kusmierz** [comment]
@WanWizard Is it now better?

**Comment by WanWizard** [comment]
I'll merge it as soon as the docs are updated. I don't have any time for it at the moment.

**Comment by kusmierz** [comment]
Should I do it?

**Comment by WanWizard** [comment]
If you want to, that will be great! 

@FrenkyNet can you keep an eye on this, and merge it when finished?

**Comment by frankdejonge** [comment]
@WanWizard will do!

**Comment by frankdejonge** [comment]
@kusmierz Any updates on this?

**Comment by frankdejonge** [comment]
Closing this due to lack of response.

**Comment by kusmierz** [comment]
@FrenkyNet sorry, I haven't time to finish it. What and where should I do to merge it with main branch?

**Comment by frankdejonge** [comment]
The pull-request must be made on the 1.4/develop branch, comply to the coding styles, and have a pull-request for docs included.

**Comment by frankdejonge** [comment]
@kusmierz since we want to get 1.4 in a relative short period, it could be that you'll have to request a pull on the 1.5 branch if 1.4 is released.

**Pull request closed without merging**
