### PR TITLE
Changed templating to make it a little more useful and consistent

### PR DESCRIPTION
**Pull request by peter-fritchley**
Changed template so that it includes the previous_start, previous_end, next_start and next_end template variables in the output. Also wrapped each of the page links to make it more consistent (and make for easier styling).

### CODE REVIEW

**Comment by jschreuder** [comment]
@WanWizard I thought we weren't going to update the Pagination class anymore but replace it entirely for the next version?

**Comment by WanWizard** [comment]
That is correct. 

There should be quite a few issues and pull requests open for this class, that are not accepted for that reason.

The reference above is an issue about this subject that I closed.

**Comment by jschreuder** [comment]
I know and I would have closed it for that reason, but you referenced this pull-request from another.

**Comment by WanWizard** [comment]
I did at that time because it was a duplicate, so I could close the other one.

**Pull request closed without merging**
