### PR TITLE
1.1/develop

### PR DESCRIPTION
**Pull request by Savageman**
Issue #810 and related

### CODE REVIEW

**Comment by Savageman** [comment]
I actually removed the `! is_dir($basepath) or ! is_writable($basepath)` inside the `append()` function since I couldn't find how it was useful...

**Comment by WanWizard** [comment]
@Savageman any progress?

**Comment by Savageman** [comment]
Hum. Didn't plan to change anything more. I though you would cherry-pick to discard the one which changes a behaviour.

**Comment by WanWizard** [comment]
ah, ok. thanks for the feedback.

**Comment by WanWizard** [comment]
Cherry-picked some ideas here: https://github.com/fuel/core/commit/c17a88336ef390ece10d655eb7da2cd3a79c6d00

**Pull request closed without merging**
