### PR TITLE
Add the controller_name property to the active Request object.

### PR DESCRIPTION
**Pull request by fgelinas**
When the controller class name is resolved by the router and saved to the Request
object, this will also save the base controller name along with it.

For example, if the loaded controller class for the request is 'Controller_Welcome',
then the controller_name would be 'welcome'.

It can then be retrieved with the following command :
  Request::active()->controller_name

### CODE REVIEW

**Comment by WanWizard** [comment]
This has been discussed before, and denied, as it is not the controller name, it is a part of the name. And by no means a unique identifier of the controller.

Can you give a use-case for this feature?

**Comment by fgelinas** [comment]
I am writing a template controller that will render a default view if no view where loaded by the action. 
This new property will correspond to the name of the view folder for this controller. 

```
    public function after($response)
    {
        [...]
        if ($this->content == '') {
            $file = Request::active()->controller_name.'\\'.Request::active()->action;
            $this->content = \View::forge($file);
        }
        [...]
    }
```

**Comment by WanWizard** [comment]
So it's application specific code, and should not be a part of the core.

It can easily be replaced by substr(Request::active()->controller, 11). And don't use '\', use the DS constant as a path separator, it makes your code platform independent.

Also consider the namespace. If you have modules your application can have multiple controllers with the same name. Which in this case would cause the wrong view to be loaded.

**Comment by fgelinas** [comment]
That will work for me, you are right to keep the core as clean as possible. 
Thanks for the advice about the directory separator and the namespace.

Good job on this framework, I like it !

**Pull request closed without merging**
