### PR TITLE
Added Inflector::pluralize_if() method

### PR DESCRIPTION
**Pull request by m4tthumphrey**
Also added 'sheep' and 'antelope' to uncountable words!

### CODE REVIEW

**Comment by m4tthumphrey** [comment]
I had actually started to write that first, but decided against it. Feel free to rewrite it!

**Comment by frankdejonge** [comment]
`$num > 1 and $word = \ Inflector::pluralize($word);` No real need for this function as far as I'm concerned. @WanWizard @jschreuder @philsturgeon ?

**Comment by WanWizard** [comment]
Agree, in this form it doesn't add anything.

I assume the idea here is to mimic gettext() behaviour, where (2, 'elephant') returns '2 elephants'. I can see a need for such a feature, but if that is required, use gettext.

Problem with this is that pluralize() is very limited, and limited to English only. Try pluralizing a Russian word... ;)

**Comment by frankdejonge** [comment]
Since it doesn't add anything significant and promotes misuse of the class (it's a tool for internal use, pluralizing tables and classes) I'm closing this.

**Pull request closed without merging**
