### PR TITLE
added profiling for mongodb queries

### PR DESCRIPTION
**Pull request by tomschlick**
added basic profiling for mongodb so they show up in the "Queries" section of the profiler

### CODE REVIEW

**Comment by billmn** [comment]
:+1:

**Comment by tomschlick** [comment]
fyi here is what one of the lines looks like in the profiler as it is now

screenshot

**Comment by frankdejonge** [comment]
@tomschlick can you put spaces around the ! and after the if's? It's in the coding style.

**Comment by tomschlick** [comment]
@FrenkyNet done

**Comment by frankdejonge** [comment]
@tomschlick one more thing: the `if ( ! empty($this->profiling))` can be `if ($this->profiling)`

**Pull request merged**
