### PR TITLE
Added create_index and drop_index functions to DBUtil class

### PR DESCRIPTION
**Pull request by zoe-edwards**
I couldn’t find this anywhere and it’s often something you add as the project grows, so it’s probably better off being completely separate to `create_table()`.

Added two functions:

```
create_index($table, $field, [ $type ] )
```

`$type` might be `unique` or `fulltext`.

```
drop_index($table, $field)
```

Pretty self explanatory.

It gives the index name the same name as the field.

### CODE REVIEW

**Comment by crynobone** [comment]
Would be nice if we can combine two or more fields to create an INDEX

**Comment by zoe-edwards** [comment]
Yeah good point, I’ll edit it if nobody beats me to it.

**Comment by philsturgeon** [comment]
I've noticed this never made it into the documentation. Could you add some examples and an explanation, then send a new pull request please?

**Comment by zoe-edwards** [comment]
Sorry I was going to expand on it to allow the combination of two or more fields. I’ll write the Docs now and do that later!

**Comment by philsturgeon** [comment]
Nono this pull request is in, done, history. Just make a new pull request on the docs repo :)

**Comment by zoe-edwards** [comment]
Ah nice, cheers!

**Comment by WanWizard** [comment]
Those two are documented as well: 411e925715c0249d207ae2e2522501a3fd898658

**Comment by philsturgeon** [comment]
I'll use grep over TextMate next time, they are indeed there:

```
grep -R "create_index" .
./classes/database/dbutil.html: <h4 class="method" id="method_create_index">create_index($table, $index_columns, $index_name, $index = '')</h4>
./classes/database/dbutil.html: <p>The <strong>create_index</strong> method allows you to create secondary indexes on a table.</p>
./classes/database/dbutil.html: <pre class="php"><code>\DBUtil::create_index('table', 'name');
```

**Pull request closed without merging**
