### PR TITLE
Add and drop foreign keys

### PR DESCRIPTION
**Pull request by peter-fritchley**
Added ability to add and drop foreign keys after a table has been created.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Possibly not a great idea, we're trying to phase out this odd "MySQL only" class not add new features to it.

**Comment by peter-fritchley** [comment]
So what is the alternative? re-writing this class to make use of the db abstraction?

**Comment by philsturgeon** [comment]
The class is being rewritten already. Just ignore it till it goes away.

Foreign keys are only supported by some engines anyhow.

Emailing from my iPhone 4S like a BOSS!

**Comment by jschreuder** [comment]
We can allow it in here, we just can't promise sustained compatibility in 2.0 (other than Legacy package).

I do have a few notes though:
- It shouldn't just return on empty input, that's not valid and thus should throw an exception (InvalidArgumentException to be precise)
- Using parenthesis is required per our [coding standards](http://docs.fuelphp.com/general/coding_standards.html), thus the same `if` statement should have them.
- It must have an accompanying pull-request to the docs with documentation of these methods.

If you're quick it may be included in 1.2.

**Comment by peter-fritchley** [comment]
Associated documentation pull request https://github.com/fuel/docs/pull/333

**Pull request merged**
