### PR TITLE
add \Str::random('uid')

### PR DESCRIPTION
**Pull request by benharold**
Add random UID generation to string class.

http://en.wikipedia.org/wiki/Universally_unique_identifier#Definition

### CODE REVIEW

**Comment by frankdejonge** [comment]
@benharold looks good, could you also update the docs?

**Comment by Art4** [comment]
I would prefer to call it with "uuid" (see RFC 4122 https://tools.ietf.org/html/rfc4122)

``` php
\Str::random('uuid');
```

**Comment by huglester** [comment]
Good point at uuid

**Comment by WanWizard** [comment]
Agree with @Art4. If changed and docs are present we can merge it.

**Comment by benharold** [comment]
After reviewing Wikipedia and the RFC, it looks like the code needs a little tweaking to conform to the standard. I'll post an update with docs when I get a chance.

**Comment by frankdejonge** [comment]
@benharold thanks, we'll keep an eye out for it.

**Comment by WanWizard** [comment]
Can you change this to UUID as requested, and send a PR to update the docs?

**Comment by benharold** [comment]
Done!

**Pull request merged**
