### PR TITLE
Module Routes

### PR DESCRIPTION
**Pull request by andrewwheal**
Made the module name get automatically added to the front of routes loaded from a module and also added support for _root_ routes in modules

### CODE REVIEW

**Comment by WanWizard** [comment]
I have mixed feelings about this. I can see this can be handy something, but I don't like magical modifications...

**Comment by andrewwheal** [comment]
I wouldn't have said it was magical modifications, all it is doing is adding the module name in front of the routes which saves you having to do it yourself. Also, it allows use of _root_ in a module which IMO is a nice feature and allows a module routes file to function exactly the same as the routes file in the app/config folder.

**Comment by phil-lavin** [comment]
This does seem to make sense and adds a level of consistency between the main routes config and the module specific routes config.

**Comment by WanWizard** [comment]
I see where you're coming from.

But the code needs to be improved. If you prefix the route with the module name, you need to check if it isn't there already, This code breaks the current module routes file, which already has the module name prefixed.

**Pull request merged**
