### PR TITLE
Feature/validation required with

### PR DESCRIPTION
**Pull request by jwalton512**
Adds new validation method which conditionally requires the completion
of a specified field based on the completion of another field

### CODE REVIEW

**Comment by jwalton512** [comment]
adds feature discussed here https://github.com/fuel/core/issues/972

**Comment by tomschlick** [comment]
+1 Great Addition

**Comment by huglester** [comment]
+1

**Comment by WanWizard** [comment]
it's a new feature, so it should be a pull request against 1.3/develop

**Comment by jwalton512** [comment]
Thought this was closed. It has already been pushed to 1.3

**Pull request closed without merging**
