### PR TITLE
Enable connection setting for migrations

### PR DESCRIPTION
**Pull request by ihildebrandt**
This is working without issue now. My problems were being caused by two things: The new migration config file was being written without an extension and the migration config file in config/ was being deleted.

### CODE REVIEW

**Comment by WanWizard** [comment]
I can't merge this, the extension issue has already been fixed elsewhere.

**Comment by ihildebrandt** [comment]
Not entirely sure why all of these commits just got reported.

**Comment by WanWizard** [comment]
this is due to the last commit, which merges the develop branch in.

Check https://github.com/fuel/fuel/wiki/Contributing on how you can prepair your feature branch for a pull request.

**Comment by ihildebrandt** [comment]
Thanks for the link, got it cleaned up.

**Comment by WanWizard** [comment]
Would you be so kind to document this new feature too?

**Pull request merged**
