### PR TITLE
fix bug, to show exception message correctly

### PR DESCRIPTION
**Pull request by KenjiOhtsuka**
I modified classes/database/connection.php to show exception message correctly.

Please check and merge.

### CODE REVIEW

**Comment by WanWizard** [comment]
Thanks. But unfortunately the wrong fix, we don't like embedded variables (it looks like old kahana code), we prefer single quotes and concatenation.

**Comment by KenjiOhtsuka** [comment]
Oh, I'm so sorry.

**Comment by WanWizard** [comment]
No problem, you want to change it (using `'text'.$var.'text'` instead, and send it a new PR?

**Comment by KenjiOhtsuka** [comment]
Thank you.
I'll make that code to 

```
'Database type not defined in "'.$name.' configuration or ...
```

And I guess code at line 70

```
$config = \Config::get("db.{$name}");
```

should be

```
$config = \Config::get('db.'.$name);
```

, and also at line 59.

I'll try.

**Comment by WanWizard** [comment]
`'Database type not defined in "'.$name.'" configuration or ...` (missing second double quote)

And yes, that is a good find too!

**Pull request closed without merging**
