### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by kenjis**
I would like to add composer.json to all FuelPHP 1.x repositories.
It could increase flexibility of composer installation.

### CODE REVIEW

**Comment by WanWizard** [comment]
In what respect? What is the use case? I don't want Fuel v1 repo's on packagist if I can avoid it...

**Comment by kenjis** [comment]
I don't want to register Fuel v1 repos on Packagsit.

If Fuel v1 repos have its composer.json, I could use "repoistories - type - vcs".

```
    "repositories": [
        { "type": "vcs", "url": "https://github.com/fuel/docs" },
        { "type": "vcs", "url": "https://github.com/fuel/core" },
        { "type": "vcs", "url": "https://github.com/fuel/auth" },
        { "type": "vcs", "url": "https://github.com/fuel/email" },
        { "type": "vcs", "url": "https://github.com/fuel/oil" },
        { "type": "vcs", "url": "https://github.com/fuel/orm" },
        { "type": "vcs", "url": "https://github.com/fuel/parser" }
    ],
```

Now we use  "repoistories - type -package". But it has a few limitations.
See Note on https://getcomposer.org/doc/05-repositories.md#package-2

And to use "repoistories - type - vcs" in "fuel/fuel" or not is another issue.
This PR only adds composer.json file.

**Comment by WanWizard** [comment]
Ok, if you have improvements on the current develop composer.json, by all means suggests improvements. The current version was a PR too.

**Comment by kenjis** [comment]
I sent PR for all repos:
https://github.com/fuel/docs/pull/666
https://github.com/fuel/orm/pull/356
https://github.com/fuel/oil/pull/232
https://github.com/fuel/auth/pull/92
https://github.com/fuel/email/pull/59
https://github.com/fuel/parser/pull/81

If they are merged, I could install Fuel in ordinary usage of Composer if I change composer.json in fuel/fuel.
I could fix revisions of all Fuel repos if I share composer.lock file.
I could update 1.8/develop Fuel with just `composer update`.

In the current way, I can't fix the revisions. Whenever I install, the latest 1.7/master or 1.8/develop branch is installed. And I can't update 1.8/develop Fuel with just `composer update`.
The limitations come from "repoistories - type - package".

**Comment by it-can** [comment]
+1

**Comment by it-can** [comment]
@kenjis http://fuelphp.com/forums/discussion/comment/18586#Comment_18586

**Comment by kenjis** [comment]
@it-can 
I tested before sending this PR.

You can test after merging all repos's composer.json into your repos, and change fuel/fuel composer.json like below (URL should be your repos):

```
    "repositories": [
        { "type": "vcs", "url": "https://github.com/fuel/docs" },
        { "type": "vcs", "url": "https://github.com/fuel/core" },
        { "type": "vcs", "url": "https://github.com/fuel/auth" },
        { "type": "vcs", "url": "https://github.com/fuel/email" },
        { "type": "vcs", "url": "https://github.com/fuel/oil" },
        { "type": "vcs", "url": "https://github.com/fuel/orm" },
        { "type": "vcs", "url": "https://github.com/fuel/parser" }
    ],
```

@WanWizard 
Those PRs only add composer.json files to repos. No side effect I think.
To use those composer.json, we still have to change composer.json in fuel/fuel.

**Comment by it-can** [comment]
@kenjis ok and how does my require section look like in composer.json?

like this?
`"fuel/core": "1.8",`

**Comment by it-can** [comment]
Okay found it, should be: `dev-1.8/develop`

**Comment by kenjis** [comment]
Yes. You can use Compser in a normal way.

**Comment by gracix** [comment]
:+1:

**Comment by itcom** [comment]
+1

**Comment by localdisk** [comment]
:+1:

**Comment by kenjis** [comment]
What would prevent this PR from being merged?

**Comment by WanWizard** [comment]
My health. Unfortunately. :cry: 

Maybe Steve or Mark can pick this up?

**Comment by kenjis** [comment]
Oh, my. Take care, please.

**Comment by sharkpp** [comment]
:+1:

**Comment by mukaken** [comment]
:+1:

**Comment by kenjis** [comment]
Someone of core developers, would you please take care of this PR?

**Comment by emlynwest** [comment]
Given that v1 is about to reach "EOL" I am not sure I see a need for this really.

**Comment by kenjis** [comment]
v2 is still in alpha. I have no idea how to update to v2.
And v1 will have LTS version. v1's end of life won't come soon.

**Comment by kenjis** [comment]
@WanWizard Thank you!

**Comment by kenjis** [comment]
I sent PR to `fuel/fuel`.
https://github.com/fuel/fuel/pull/306

Any comments are welcome.

**Pull request merged**
