### PR TITLE
Fix #1857 of the official repo

### LINKED ISSUE #1857: Unable to use multipart/form-data
**The Problem**
[POST, PUT, and DELETE requests](https://github.com/fuel/core/blob/1.8/develop/classes/request/curl.php#L254) through \Request_Curl only use supported formatting types or they [default to x-www-form-urlencoded](https://github.com/fuel/core/blob/1.8/develop/classes/request/curl.php#L347) which is [terrible for longer request types](http://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data).

There currently isn't any way (that I know of) to force an array to CURLOPT_POSTFIELDS to allow for multipart/form-data requests, though every other format is possible.

**Proposed Solution**
To allow an array to be directly set to CURLOPT_POSTFIELDS, create a method to set a property flag to true when the functionality is needed. Developers can call that method when they wish to allow for such functionality.

### PR DESCRIPTION
**Pull request by rickmacgillis**
Allow cURL requests to make requests as multipart/form-data

### CODE REVIEW

**Comment by rickmacgillis** [comment]
Are you still waiting on something from me before you merge my pull request?

**Comment by WanWizard** [comment]
Yeah, docs?

**Comment by rickmacgillis** [comment]
Where do you want me to document it?

**Comment by emlynwest** [comment]
https://github.com/fuel/docs

**Comment by WanWizard** [comment]
On the Request, Curl page, in the correct method docs. Perhaps as a note, explaining how to pass the 'array' value, and what it exactly does.

**Comment by rickmacgillis** [comment]
Alright, I've edited the docs, and created a [pull request](https://github.com/fuel/docs/pull/686) for them.

**Comment by rickmacgillis** [comment]
Is there something else I need to do to get the ball rolling on this pull request?

**Comment by rickmacgillis** [comment]
Any idea on when you'll have time to merge this pull request? Is there something I can do to speed it along? It's been half a month already.

**Comment by WanWizard** [comment]
I've been completely cut of from internet the last few weeks, and still am. So it took a while, sorry about that.

**Comment by rickmacgillis** [comment]
It's alright. You're usually quite punctual, so I was wondering what happened. Thanks for merging it in!

**Pull request merged**
