### PR TITLE
Remove ORDER BY from sql count_last_query

### PR DESCRIPTION
**Pull request by bernhardh**
Since we don't need "ORDER BY" on count statements and its slows down some queries, we can remove it

### CODE REVIEW

**Comment by WanWizard** [comment]
This regex seems to strip everything starting with the `ORDER BY`

So `OFFSET 0 ORDER BY table.field LIMIT 10` will become  `OFFSET 0`, and not `OFFSET 0 LIMIT 10`

**Comment by bernhardh** [comment]
I know, but thats not a problem, since we don't need OFFSET or LIMIT as well (and we remove both of theme some lines above:

```
        if (stripos($sql, 'LIMIT') !== false)
        {
            // Remove LIMIT from the SQL
            $sql = preg_replace('/\sLIMIT\s+[^a-z\)]+/i', ' ', $sql);
        }
        if (stripos($sql, 'OFFSET') !== false)
        {
            // Remove OFFSET from the SQL
            $sql = preg_replace('/\sOFFSET\s+\d+/i', '', $sql);
        }
```

**Comment by WanWizard** [comment]
Maybe I used the wrong example. The regex strips anything, it could also be an `GROUP BY` for example. The other regexes only strip the keyword and it's value.

**Comment by bernhardh** [comment]
You are right.
Please have a look at the following regex (and usecases): https://regex101.com/r/jS5fN1/5
(Thanks to User vks from StackOverflow). 

Have I overseen another possible situation?

**Comment by WanWizard** [comment]
That looks a lot better!

**Comment by WanWizard** [comment]
This regex doesn't deal with ASC or DESC which can be part of the ORDER BY clause.

**Pull request closed without merging**
