### PR TITLE
Allow override of method_params from Request execute()

### PR DESCRIPTION
**Pull request by phil-lavin**
This facilitates the passage of objects, arrays, etc. when using Request in a HMVC context. My understanding is that currently you can only pass string data into a controller/method in a HMVC request.

### CODE REVIEW

**Comment by nerdsrescueme** [comment]
Would an array_merge be more beneficial here so you could add to, not replace the method_params property?

**Comment by dhrrgn** [comment]
I like this.  Not sure about @nerdsrescueme's suggestion tho.  I think it is a "one or the other" type of situation.

**Comment by jschreuder** [comment]
My only gripe with all of this is that it might get a little unclear when the URI contains params too. When the URI contains segments and there are segments passed as array it's kind of weird to just ignore the URI. After a bit of thinking I think I agree with @nerdsrescueme's suggestion, by merging them you put the URI's segments first and make the passed args the "additional arguements" instead of a replacement. You can still use only passed arguements by not passing any through the URI, but you're not overwriting anything.

Another possible pitfall is if we might need to add another first param to Request::execute(), but passing additional args seems a logical param so I don't think that's a problem.

**Comment by Savageman** [comment]
Very useful in HMVC context! I like this feature. :-)

**Pull request merged**
