### PR TITLE
html fieldset support, preliminary

### PR DESCRIPTION
**Pull request by CoolGoose**
I'm open to improvements :) It's a bit hack-ish right now.

### CODE REVIEW

**Comment by jschreuder** [comment]
If you remove it from the `build_field()` method I'll merge it, `fieldset_open` and `fieldset_close` aren't fields and shouldn't be used like that (I have other plans for that: #320).

**Comment by CoolGoose** [comment]
Should i keep it to be used with $form->add or do you want it like $form->fieldset_open ?

**Comment by jschreuder** [comment]
@Coolgoose read the issue I referred to, it'll be possible to nest Fieldset instances into Fieldset instances and after that the nested Fieldset instances will use the `<fieldset />` tags and it'll be possible to specify form or fieldset tag for the "root" Fieldset instance.

Thus `Form::fieldset_open()` for now (though $form->fieldset_open() would work as well to get the code), real OO support will have to wait and will certainly never be done with the add() method.

**Comment by CoolGoose** [comment]
Like so ?

**Comment by jschreuder** [comment]
Yeah, but I'm not yet sure about the $legend param. It would feel better if this method was more like the `Form::open()` method. But where Form::open() either takes attributes or the action, it would feel wrong to allow here the "legend" instead of the attributes (action and legend are too different). I think it would be best to swap the params and allow "legend" as a key in attributes as well:

``` php
<?php
public static funnction fieldset_open(array $attributes = array(), $legend = null)
{
    ! is_null($legend) and $attributes['legend'] = $legend;
    // etc... (and use $attributes['legend'] after this instead of $legend)
}
```

Also prefix the `!` with a space on line 150, the code guidelines say that they must have spaces on both sides.

**Comment by CoolGoose** [comment]
Better ? :D

**Comment by jschreuder** [comment]
I'll fix up the last things myself: next time use my code as it would have prevented the double code for the `<legend>` tag and `elseif` is one word.

**Comment by jschreuder** [comment]
@Coolgoose Can you also add your methods to docs?

**Comment by CoolGoose** [comment]
Asap i'm going to do a pull on the 1.1-dev docs (today in any case)

**Pull request merged**
