### PR TITLE
Adding exceptions to the date class to make catching and handling unexpe...

### PR DESCRIPTION
**Pull request by bencorlett**
...cted values easier.

This makes it possible to catch an error when date's aren't valid and take action appropriately, instead of getting a warning show up and do nothing about it.

Signed-off-by: Ben Corlett bencorlett@me.com

### CODE REVIEW

**Comment by frankdejonge** [comment]
I think an UnexpectedValueException would be more in order. @jschreuder ?

**Comment by jschreuder** [comment]
First of all: Thanks @bencorlett, this has needed doing for some time and I kept putting it off.

But I agree with @FrenkyNet, there's no real reason for a specialized exception here. Just the unextended `\UnexpectedValueException` would be fine.

**Comment by bencorlett** [comment]
Okay will fix that in the morning :)

**Comment by bencorlett** [comment]
Sorry mate forgot all about it. I'll do it now.

**Comment by bencorlett** [comment]
There ya go @jschreuder

**Pull request merged**
