### PR TITLE
Added method to alter table.

### PR DESCRIPTION
**Pull request by peter-fritchley**
Method added so that tables can be altered, this mimics the alter_fields method but allows new foreign keys to be defined

### CODE REVIEW

**Comment by WanWizard** [comment]
This functionality is already present in the form of the drop_fields(), alter_fields() and modify_fields() methods.

**Comment by peter-fritchley** [comment]
That's true, but there is no way of adding foreign keys to the database after the point of which the table has been created - functionality that is needed if you are using migrations to generate a database that has two tables that have foreign keys to one another.

Would my time be better spent adding a simple function to add primary keys? similar to how the create_index works?

**Comment by WanWizard** [comment]
Primary keys should be added when you create the table. It's a bit pointless to do that afterwards, then your migrations are clearly wrong.

As to foreign keys, I understand your point, but would prefer to add the functionality to the existing methods, so they work similar to create_table().

**Comment by peter-fritchley** [comment]
Yeah, i meant foreign keys - not primary keys. I agree that it should work in the same way as create table, but couldn't find where it would logically fit into any of the existing functions.

**Pull request closed without merging**
