### PR TITLE
Set the $_POST or $put_delete based on php://input on "applicaiton/json" request

### PR DESCRIPTION
**Pull request by tgriesser**
When a request is sent as "application/json" (typical in backbone.js applications) rather as the standard  application/x-www-form-urlencoded or multipart/form-data, the data in the header payload should be json_decoded and used as the request input.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Why are you trying to confuse POST variables and HTTP body? POST vars are a combination of HTTP body with a specific MIME Type as you have already suggested, everything else is just HTTP doing its thing. Why should JSON be given preference? Why not XML? Or CSV? Or JPG?

Leave HTTP well alone, it's fine as it is.

**Comment by tgriesser** [comment]
It seemed intuitive for the Controller_Rest, that if a put or post request comes in with a content/type of "application/json", the JSON variables could be accessed via Input::post('key') or Input::put('key'), rather than needing to emulate the structure in a urlencoded form on the client side.

And JSON was given preference because it's structure mimics php's array. I don't know how you'd easily go about putting the other structures into associative arrays.

See : 
  http://fuelphp.com/forums/topics/view/3737
  http://saaboke.com/?p=207

Not trying to step on HTTP's toes, just looking for a practical solution for something that (for me at least) is a common use case.

**Comment by philsturgeon** [comment]
The two are nothing to do with each other. A body is perfectly allowed but should not be forced into the $_POST structure because that is entirely irrelevant.

**Comment by tgriesser** [comment]
What about this: https://github.com/tgriesser/core/commit/53c7db3df06689a9b148076bd0078add497cae37

**Comment by frankdejonge** [comment]
That url is hidden from me? Can't look at it.

**Comment by frankdejonge** [comment]
Fixed differently: https://github.com/fuel/core/blob/1.1/develop/classes/input.php#L57

**Pull request closed without merging**
