### PR TITLE
Fixed a bug when running PHPUnit with views being loaded multiple times.

### PR DESCRIPTION
**Pull request by drewsonne**
When running phpunit tests and creating a controller, if I use a dataProvider and call the same controller again and again with different data, I get errors ("Cannot redeclare my_function_name()") with functions defined in the global scale.

### CODE REVIEW

**Comment by WanWizard** [comment]
That include just loads the View file, that should not contain code?

**Comment by drewsonne** [comment]
The project I'm building test cases for has code in there as view helpers. I appreciate that by FuelPHP view docs there's no mention of class/function declaration in the views, but they're being used as view helpers, to avoid copy/paste code associated specifically with the presentation layer.

**Comment by WanWizard** [comment]
We believe code in a view is bad practice. 

If you need generic helpers, you can define them outside the views, either as static class methods, or as traditional functions. If they are specific helpers for that view, you should move the processing to a Viewmodel (Presenter pattern), and abstract it from the View. Ideally, it should only contain HTML, and some simple if or loop structures.

**Comment by pendexgabo** [comment]
I agree with @WanWizard . The separation between views and anything else is pretty clear (and the view implementation is clean)...so if your patch is applied you won't be able to reuse (AKA `forge` again) such view since was already included...

**Pull request closed without merging**
