### PR TITLE
Log Enhancements

### PR DESCRIPTION
**Pull request by dbpolito**
Pull Request related to #1125

I think that would be a great addition to the framework some enhancements to log:
1. Changes Log to be Driver-Based
   - Makes possible to have logs stored on file or database simply changing on config (similar to session).
2. Makes easier to understand custom levels.
3. Creates an Event (log_called for example) so we can easily use that for example to send an e-mail if we get error log.

**Important Note:** This change will not make any application crash, only will be need a heads up about configuration because it moves from config.php to a log.php file.

This is an initial commit so i can get feedback and see if it's getting good.

Still pending:
1. Makes an Oil Task for create the logs table as we have on session.
2. Change Docs
3. Event for Log Calls

Let me know your thoughts.

### CODE REVIEW

**Comment by tomschlick** [comment]
+1

**Comment by tomschlick** [comment]
My only suggestion for this would be to add the ability to change the location / filename of the file based logs. For instance I prefer to have logs created for each hour instead of each day so i may want to format mine like LOGPATH/2012/08/23/02.php

**Comment by WanWizard** [comment]
@dbpolito any proogress? If so, can you re-submit against 1.4/develop?

@tomschlick's suggestion could be implemented by allowing strftime() tokens in the "log_path" config key, and expand that when it's used to create the correct foldername/filename prefix.

**Comment by dbpolito** [comment]
I think we can continue this one in the new pull request. Thanks.

**Pull request closed without merging**
