### PR TITLE
Temporary Fix for #835

### PR DESCRIPTION
**Pull request by lukearmstrong**
https://github.com/fuel/core/issues/835

### CODE REVIEW

**Comment by jschreuder** [comment]
We don't accept temporary fixes into the core: either it fixes it or it doesn't.

**Comment by lukearmstrong** [comment]
It fixes the issue, and after using it for a day on a large site that uses a lot of the functionality of Fuel I haven't encountered any problems.

It works if the URL has parameters after the extension, and it works if the URL does not have parameters after the extension.

The only reason I called it temporary is because it doesn't use Regex, and it may be possible to write the same thing in less lines than I have done if the current Regex was fixed. But as I don't know Regex that well, I opted to use a more long winded method I know would work.

Perhaps I should have had more confidence when submitting this pull request, but it's up to you if you want to disregard a working solution and continue with a broken core.

**Comment by jschreuder** [comment]
I'll say 2 things to this:
1. We all have shit to do, like work and actual lives that are seriously more important to us than any volunteer work. If you don't think your fix is good enough why should I even take the time to check it out? Especially when you explain WHY it's not good enough. (I did check it out btw)
2. Check my answer to the issue you say this solves and you'll see I don't consider this a bug. Thus no broken core. Also even if it did somehow fix something in a bad way, that's just asking for trouble. I never accept bad code, unexplained code or unfinished code - even if it does seem to fix something. Fix something good or not, there're no halfway fixes because the trouble you may cause by bad/unexplained/unfinished code is often a cure that turns out worse than the disease.

**Comment by lukearmstrong** [comment]
1. Well that was my mistake, I should have had more confidence in it. I'm very aware that some people think differently, they look at a problem like that and think that regular expressions should be used to solve it, as the previous person did.
2. There is a comment explaining what each line of my pull request does. It is not badly written, nor is it unfinished, but I am aware that it could have been written differently.

**Pull request closed without merging**
