### PR TITLE
enable create table in sqlite3

### PR DESCRIPTION
**Pull request by KenjiOhtsuka**
Modified classes/dbutil.php to enable create table in sqlite3.
Previous code can't create table with primary index in sqlite3,
because previous code generate

``` sql
PRIMARY KEY 'id' ('id')
```

but sqlite3 supports

``` sql
PRIMARY KEY ('id')
```

I used config/db.php setting string to check whether the database is sqlite3.

The following code using `Database_Connection` is another way to do it.

``` php
$sql .= ",\n\tPRIMARY KEY ";
if (strtolower(\Config::get('db.'.($db ? $db : \Config::get('db.active')).'.type')) === 'pdo')
{
  if (strtolower(\Database_Connection::instance($db)->driver_name()) !== 'sqlite')
  {
    $sql .= $key_name;
  }
}
$sql .= $key_name." (" . implode(', ', $primary_keys) . ")";
```

### CODE REVIEW

**Comment by kenjis** [comment]
If you use PDO and not SQLite, `$key_name` is duplicated. See #1943

**Comment by WanWizard** [comment]
This code is not correct, the key name is not needed there at all, MySQL just ignores it when it's there, I haven't checked the other RDBMS syntax yet.

**Comment by WanWizard** [comment]
Checked all PDO supported RDBMS engines:
- DB2, Cubrid, Informix, MSSQL, PostgreSQL and SQLite do not accept a key name at all
- MySQL does accept a keyname, but ignores it if it is there
- Firebird, Oracle: SQL syntax not supported by Fuel's DBUtil

So there should not be a key/constraint name at all, that is only relevant for secondary indexes.

**Comment by KenjiOhtsuka** [comment]
I'm so sorry.
So should it be like below?

``` php
$sql .= ",\n\tPRIMARY KEY (" . implode(', ', $primary_keys) . ")";
```

**Comment by WanWizard** [comment]
Instead of the code snippet above? Yes, I think it's as simple as that. 

No constraint or key name in all cases, only Oracle requires a constraint name, and Firebirds SQL syntax is completely diffferent, but we don't support those anyway.

If you can amend your PR, and test it, then I'll merge the update.

**Comment by KenjiOhtsuka** [comment]
I changed the code and tested with MySQL, SQLite and PostgreSQL.

I'm plannig to test with DB2, Cubrid, Informix, MSSQL.

Which branch should I create PullRequest to? 1.8/develop?

**Comment by KenjiOhtsuka** [comment]
@WanWizard 

I created new PR below.
https://github.com/fuel/core/pull/1947

**Pull request merged**
