### PR TITLE
the rules of 'Inflector' are load in config file.

### PR DESCRIPTION
**Pull request by diegoszch**
I removed Inflector's rules of the array to config file, because in latin language the grammatical rules follow different patterns and today I can't change this values.

Thus, the core stayed more flexible.

### CODE REVIEW

**Comment by emlynwest** [comment]
How would this work for apps where there are multiple languages? Eg, my app can be in English and Chinese and the user can select which language they want.

**Comment by diegoszch** [comment]
Interesting @stevewest . 
Primarily I wanted remove the rules of the code e put it in config file.

But, do you think better to put the file in lang folder instead of config folder?

**Comment by emlynwest** [comment]
This is something that is dependant on the enabled language so it would be work making it obey the currently active language.

From the docs: `Config::set('language', 'cy');`
http://fuelphp.com/docs/classes/lang.html

I think it is good to make inflector language aware but it should be done in a flexable way that allows for configs for multiple languages, not just one at a time.

**Comment by diegoszch** [comment]
Ok...I'm going to close pull request and change my code to respect these conditions.

Thanks @stevewest.

**Pull request closed without merging**
