### PR TITLE
Fixed issue #997 : Label "for" does not match Input "id" in fieldsets

### PR DESCRIPTION
**Pull request by billmn**

### CODE REVIEW

**Comment by WanWizard** [comment]
@jschreuder could you have a look at this when you have the time?

**Comment by WanWizard** [comment]
@jschreuder @FrenkyNet any one that can check this? Fieldsets isn't my thing... ;-)

**Comment by jschreuder** [comment]
I'll try and find the time. This is a recurring problem because any fix to it breaks it somewhere else. It's a conflict between the Form & Fieldset logic.

**Comment by billmn** [comment]
@jschreuder do you think that can be solved?

I think that create tests also for the Form class can be useful to identify conflicts

**Comment by jschreuder** [comment]
@billmn that'd be the best approach. I've attempted to solve this twice already and I'm afraid the problem is that part of the current functionality is based on buggy behavior.

**Comment by WanWizard** [comment]
I see there's a similar test in the Fieldset test class, so it looks like this was fixed elsewhere.

**Pull request closed without merging**
