### PR TITLE
Arr::get can return keys including dots

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by WanWizard** [comment]
@FrenkyNet ok? This needs to be changed in the v2 code too then.

**Comment by huglester** [comment]
probably isset() would be faster by some nano seconds and with same benefit?

**Comment by sagikazarmark** [comment]
What about null values?

**Comment by huglester** [comment]
I am not following something maybe?

``` php

>>> $a = array('a' => 1, null => 3);
>>> isset($a[null]);
true
>>> array_key_exists(null, $a);
true
```

and if I have no null values, both commands return some error from cli

**Comment by frankdejonge** [comment]
@huglester, that's null index not null values, and he's correct.

**Comment by WanWizard** [comment]
$key will never be null there, a null value has been checked and dealt with before you get here.

This PR is about keys, not about values, so I'd have to say I don't understand the remark either.

**Comment by sagikazarmark** [comment]
```
$array = ('some.key' => null);

//returns false
isset($array['some.key']);

//returns true
array_key_exists($array, 'some.key');
```

So the isset check for the array ELEMENT (identified by the key) returns false, if the value is null.

**Comment by WanWizard** [comment]
Hmm... must have been sleeping...

**Pull request merged**
