### PR TITLE
Update classes/controller/rest.php

### PR DESCRIPTION
**Pull request by quetzyg**
Remove forgotten type hint from Fuel\Core\Controller\Rest::router()

### CODE REVIEW

**Comment by WanWizard** [comment]
Why that? This type hint has always been there, no need to remove it. It only had to be removed from Controller, because it was never there in the past...

**Comment by quetzyg** [comment]
Well, because the Controller_Rest class extends the Controller class, and I get notices about declaration compatibility when using the Hybrid/Rest Controller.

```
Runtime Notice!

ErrorException [ Runtime Notice ]: Declaration of Fuel\Core\Controller_Rest::router() should be compatible with Fuel\Core\Controller::router($resource, $arguments)
```

**Comment by WanWizard** [comment]
Ah, chips, didn't think of that.

**Comment by quetzyg** [comment]
:+1:

**Pull request merged**
