### PR TITLE
Only look in child fieldsets when $flatten is true

### PR DESCRIPTION
**Pull request by Altreus**
`$flatten` appears to decide whether we should recursively treat child fieldsets' fields as our own; the behaviour of `$fieldset->field('name')` should be the same as `$fieldset->field()['name']` - which is only valid for newer PHPs.

### CODE REVIEW

**Comment by emlynwest** [comment]
What exactly is the issue here?

**Comment by Altreus** [comment]
If you add a child fieldset with a particular field name, say `ids[]`, you can't then add a field with that name to the parent fieldset, because it will eventually do `$this->field('ids[]')`

This is not consistent with `$this->field()['ids[]']`, which would return a different result (i.e. not there), and is a perfectly valid thing to do.

This solution therefore only recurses into child fieldsets when the method call has `$flatten = true`

**Comment by emlynwest** [comment]
When you say "a child fieldset" you do mean a child field? I am just trying to find out what the actual problem here so I can better assess your change.

**Comment by Altreus** [comment]
No I mean a child fieldset

```
$fieldset = \Fieldset::forge('parent');
$child = \Fieldset::forge('child');
$child->add('ids[]', null);
$fieldset->add($child);
$fieldset->add('ids[]', null);  // error
```

**Pull request closed without merging**
