### PR TITLE
Remove public folder from URL

### PR DESCRIPTION
**Pull request by dbpolito**
fuel.php changed to remove public folder from url based on config.php flag

### CODE REVIEW

**Comment by dbpolito** [comment]
Pull Request related
https://github.com/fuel/fuel/pull/256

**Comment by WanWizard** [comment]
What exactly are you trying to achieve here?

If you use rewriting, the public folder is not part of the URI. If you don't, the public folder must be part of the URI.

**Comment by dbpolito** [comment]
Well, i'm using rewriting the the it's getting public here even the url have not. So here the url is localhost/fuel/posts and the generated link are localhost/fuel/public/post.

Thoughts?

**Comment by johnnyfreeman** [comment]
The "public" folder is the public document root folder. The "fuel" folder is above root. See http://docs.fuelphp.com/installation/instructions.html#/manual

**Comment by WanWizard** [comment]
And according to that same page (http://docs.fuelphp.com/installation/instructions.html#/install_inside_root) you should use a rewritebase to remove /public when rewriting. RTFM.

**Comment by dbpolito** [comment]
I don't know if it's only happening here but i'm using this .htaccess and the URL is working properly but when i use an Html::anchor('posts/create', 'Add new Post'); the link generated is fuel/public/posts/create and give me error, then i have to change the url manually to fuel/posts/create and it works. Do you know what i mean?

**Comment by WanWizard** [comment]
I you use the recommendation in the docs, with the rewritebase, the URI passed to the frontcontroller shouldn't contain /public, so no URI generated by FuelPHP will.

What does `echo $_SERVER['script_name'];` contain? If it contains /public, you have a confguration error.

**Comment by dbpolito** [comment]
The page http://localhost/fuel/ has the SCRIPT_NAME /fuel/public/index.php

Is it only here? I'm using  PHP Version 5.3.6-13ubuntu3.2 with the default configuration. Here is my phpinfo page http://pastebin.com/t1S5V0xy

**Comment by WanWizard** [comment]
Fuel can not detect whether or not the rewriting is configured properly. If you have a non-standard installation (which you have), you can fix this in the standard config file:
- set your index.php value to false
- set the base_url to `\Input::protocol().'://'.\Input::server('http_host').'/',`

No need to add something to the core code for this special case.

**Pull request closed without merging**
