### PR TITLE
Allows to pass params to process input data in Format::forge()

### PR DESCRIPTION
**Pull request by billmn**
For example the delimiter of CSV string

### CODE REVIEW

**Comment by billmn** [comment]
I've closed this pull cause I think that _form_csv can be more cleaner using str_getcsv ... I'm going to rewrite this method

**Comment by philsturgeon** [comment]
It's not about being clean, its about working properly. Using str_getcsv if you have multiple lines in a field it will break.

The built in PHP functions are terrible, why do you think I wrote all this code?

**Comment by billmn** [comment]
I didn't know that you are wrote this method

During the implementation I saw this problem, so I've mantained your code ... I'm trying only to allow to pass parameters like delimiter, enclosures and escape char

**Comment by billmn** [comment]
There's a new pull ... https://github.com/fuel/core/pull/959

**Comment by philsturgeon** [comment]
Thanks, im not against improvements I am just explaining why I went to the effort of avoiding the pre-built methods. :)

**Comment by billmn** [comment]
Sure, and your reasons are right! :)

The CSV method needs the support for delimiters because Excel 2007 allow to specify a delimiter on import, but not on export (only ";") !!!!

#excel fail

**Pull request closed without merging**
