### PR TITLE
Add flip() method to the image class

### PR DESCRIPTION
**Pull request by ronan-gloo**
Allow vertical and / or horizontal image flipping.

The method requires one of the following parameters: `vertical`, `horizontal`, `both`

```
$image::load('some/image.jpg')->flip('vertical');
```

### CODE REVIEW

**Comment by frankdejonge** [comment]
Looks good! Can you add documentation for this?

**Comment by ronan-gloo** [comment]
Pull request sent in the doc repository

**Comment by frankdejonge** [comment]
@sonotone there is no pull-request in the docs repo

**Comment by ronan-gloo** [comment]
Sorry, i've forgotten to PR it ! Done.

**Pull request merged**
