### PR TITLE
Update XML boolean format.

### PR DESCRIPTION
**Pull request by aaharu**
## XML Schema

http://www.w3.org/TR/xmlschema-2/#boolean

> An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}.
## FuelPHP behaviour

``` php
array('true' => true, 'false' => false)
```
### current format

``` xml
<xml><true>1</true><false/></xml>
```

`false` is formatted to empty string.
It's PHP type casting works.
http://php.net/manual/en/language.types.string.php#language.types.string.casting
### new format

I add `bool_representation` option to change XML outputs.

If `bool_representation` is 
`true`:

``` xml
<xml><true>true</true><false>false</false></xml>
```

`1`:

``` xml
<xml><true>1</true><false>0</false></xml>
```

false value, such as `null`:

``` xml
<xml><true>1</true><false/></xml>
```

Signed-off-by: Haruaki Otake aaharu@hotmail.com

### CODE REVIEW

**Comment by emlynwest** [comment]
Would need docs too please.
@WanWizard Thoughts on BC for this?

**Comment by WanWizard** [comment]
Not happy about it, as it breaks BC.

I understand the need for this change, perhaps use the 'null' value of the flag as default, and use that for the current behaviour, and true/false for the new behaviour?

**Comment by aaharu** [comment]
Thanks for comments.
I fix the default.

**Comment by WanWizard** [comment]
Thanks!

**Pull request merged**
