### PR TITLE
Added numeric_between validation

### PR DESCRIPTION
**Pull request by billmn**

### CODE REVIEW

**Comment by WanWizard** [comment]
Isn't this the same as specifying both a min and a max value?

**Comment by billmn** [comment]
Yes but is more concise ... imagine :

<pre>
// Validation
->add_field('ten', 'Number', 'numeric_between[9,11]');
->add_field('ten', 'Number', 'numeric_min[9]|numeric_max[11]');
// Fieldset
->add_rule('numeric_between', array(9,1))
->add_rule('numeric_min', array(9))->add_rule('numeric_max', array(11))
// ORM
'field' => array(
    'validation' => array(
        'numeric_between' => array(9, 11)
    ),
)
'field' => array(
    'validation' => array(
        'numeric_min' => array(9),
        'numeric_max' => array(11),
    ),
)
</pre>

What about you?

**Comment by huglester** [comment]
I was missing something like this. +1 :)

**Comment by WanWizard** [comment]
Between 9 and 11 is only 10, right?

**Comment by billmn** [comment]
Personally, I thought to include ... so between[9,11] => 9,10,11

**Comment by billmn** [comment]
I haven't motivated my choice.
I would include the extreme numbers because I don't want to force to make mental calculations.

:-1:  [9,20] ... so, 9+1 and 20-1

but only from 9 to 20 ... simple

**Comment by WanWizard** [comment]
Ok. Can you add the docs for this rule? Then it can be merged.

**Comment by billmn** [comment]
I've already sent it : https://github.com/fuel/docs/pull/455

**Comment by WanWizard** [comment]
Sorry, missed that.

**Comment by billmn** [comment]
Any news?

**Comment by WanWizard** [comment]
Yeah, no time. It's on the todo list ;)

**Pull request merged**
