### PR TITLE
Redis multiple databases per connection support

### PR DESCRIPTION
**Pull request by taha**
Uses Redis [select command](http://redis.io/commands/select) to switch databases on object instantiation

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you also send a PR to update the docs?

**Comment by taha** [comment]
Docs PR https://github.com/fuel/docs/pull/600

**Comment by indigofeather** [comment]
Hello @WanWizard
The Docs PR has Merged but this not

**Comment by WanWizard** [comment]
Hmm... Oops...

**Pull request merged**
