### PR TITLE
Fix config variable and simplify connection

### PR DESCRIPTION
**Pull request by it-can**
@WanWizard this is a fix for the incorrect config variable you commited in https://github.com/fuel/core/commit/cd3603c0cd4523c9c94cb4f6833d09ae907034e7
I also simplified the way the connection is done...

### CODE REVIEW

**Comment by WanWizard** [comment]
Thanks! I assume the rest was ok then?

**Comment by it-can** [comment]
@WanWizard almost...

Now getting this error, with PDO and MySQLi with cache disabled and using the current() function

```
Fuel\Core\PhpErrorException [ Notice ]:
Undefined offset: -1

COREPATH/classes/database/pdo/cached.php @ line 100
```

**Comment by WanWizard** [comment]
Grmpfff.

**Comment by WanWizard** [comment]
Pushed a fix.

**Comment by it-can** [comment]
Cool will test tomorrow

**Comment by WanWizard** [comment]
Thanks again!

**Comment by it-can** [comment]
ok seems to work...

**Comment by WanWizard** [comment]
Cool, thanks for the feedback!

**Pull request merged**
