### PR TITLE
Adds a inactive support to inactive links in Pagination class

### PR DESCRIPTION
**Pull request by kriansa**
Adds a better support to customize the unclickable links << Previous and Next>> when they're inactive(when you're in first or last page), so we can set a custom CSS class on them.

### CODE REVIEW

**Comment by crynobone** [comment]
Similar to pull request #525

**Comment by WanWizard** [comment]
Pagination class functionality will be reviewed after v1.1.

**Comment by kriansa** [comment]
May I ask why? There will be another class with its funcionality?

**Comment by WanWizard** [comment]
We're not happy with the current class, it's bloated, and contains to much stuff that belongs in the app, not in a core class.
As we're in feature freeze for v1.1. now, nothing can be done about it untill that is released.

I created a new issue for this so it stays on the radar for the next milestone.

**Pull request closed without merging**
