### PR TITLE
Arr Class add method, insert value(s) into a random iteration array

### PR DESCRIPTION
**Pull request by takecore**
Insert value(s) into a random iteration array

### CODE REVIEW

**Comment by WanWizard** [comment]
@FrenkyNet ?

**Comment by frankdejonge** [comment]
I don't really see the use-case. The `$values` parameter could be type-casted so there's no double code. So if that's fixed it can go in when there are docs supplied.

**Comment by takecore** [comment]
@FrenkyNet 
I'm sorry do not write the use-case.

here is a use-case example.

I has 2 models which Model_Article and Model_Advertisement.
I want to display both an array.
and insert Advertisements array to Articles array irregularly.
so, one foreach, then display both contents.

thanks reading.

**Comment by hackoh** [comment]
@takecore 
I think that this is a very exceptional use-case.
It is not the responsibility range of the Core.

**Pull request closed without merging**
