### PR TITLE
Removed typecasting of values to strings because it makes querying using MongoIds impossible

### PR DESCRIPTION
**Pull request by alexbilbie**

### CODE REVIEW

**Comment by alexbilbie** [comment]
FYI, bug was noticed by @tomschlick

**Comment by tomschlick** [comment]
Tried this on my local copy and it seemed to fix the problem.

**Comment by WanWizard** [comment]
I thought this was introduced as a security measure, to avoid Mongo's version of No-SQL injection?

See http://www.idontplaydarts.com/2010/07/mongodb-is-vulnerable-to-sql-injection-in-php-at-least/

**Comment by philsturgeon** [comment]
Agreed, is this not intended to escape stuff? How else can we avoid the injection issue.

**Comment by alexbilbie** [comment]
I always typecast before I call the library functions, e.g.

$this->mongo_db->where(array('username' => (string)$username))->get('users');

The problem with assuming strings is that you then can't use arrays, ints, floats, etc.

**Comment by alexbilbie** [comment]
Just checked the PHP documentation [1] and it says that you should typecast before working with the database, but by typecasting everything as strings as I said before means you can't use integers, floats or arrays.

At the end of the day you should be sanitizing all data before inserting it into any DB not just Mongo

[1] http://php.net/manual/en/mongo.security.php

**Comment by philsturgeon** [comment]
Sustained! Out it comes.

**Pull request merged**
