### PR TITLE
Fix log folders permission

### PR DESCRIPTION
**Pull request by kenjis**
`mkdir` mode is modified by the current umask.

### CODE REVIEW

**Comment by WanWizard** [comment]
The problem with umask is that it isn't thread-safe, and the new PHP installs become more and more multi-threaded. It is safer to replace the mode by a separate chmod call after the mkdir.

**Comment by kenjis** [comment]
Thanks for your comment. I've changed.

**Comment by WanWizard** [comment]
Where did this extra mkdir come from? The filepath comes from the config, it's possible it doesn't start with the year at all. 

And perhaps the @ should be removed (it is very slow), and put the mkdir in a try/catch block to capture errors if there are no rights to create the path. Now it silently fails, which can't be a good thing.

**Comment by kenjis** [comment]
See https://github.com/fuel/core/blob/1.6/develop/classes/log.php#L51

``` php
$filepath = \Config::get('log_path').date('Y/m').'/';
```

I did not change anything. It starts with the year, and the month.

Removing @ seems to be good idea.

**Comment by WanWizard** [comment]
Sorry, missed that. Been fixing stuff for two days strait, can't see properly anymore. :laughing: 

I'll merge and add the try/catch.

**Comment by kenjis** [comment]
Thank you. Great job!

**Pull request merged**
