### PR TITLE
Changed to allow replication connection

### PR DESCRIPTION
**Pull request by hackoh**
This change allows replication connection.

When you want to use replication feature, you can set the flag in db.php.

``` php
<?php
return array(
    'default' => array(
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=default',
            'username'   => 'dbuser',
            'password'   => 'dbpass',
        ),
    ),
    'db1' => array(
        'type'        => 'pdo',
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=db1',
            'username'   => 'dbuser',
            'password'   => 'dbpass',
        ),
        'identifier'   => '`',
        'table_prefix' => '',
        'charset'      => 'utf8',
        'enable_cache' => true,
        'profiling'    => false,
    ),
    'db2' => array(
        'type'        => 'pdo',
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=db2',
            'username'   => 'dbuser',
            'password'   => 'dbpass',
        ),
        'identifier'   => '`',
        'table_prefix' => '',
        'charset'      => 'utf8',
        'enable_cache' => true,
        'profiling'    => false,
    ),
    'replication' => array(
        'enable' => true,
        'master' => array('db1'),
        'slave' => array('db1', 'db2'),
    )
);
```

Only Database_Query_Builder_Select uses the slave connection.
And other queries use the master connection.

Respectively, specify the multiple connection name, the destination is a random lottery.

I want your opinion.

### CODE REVIEW

**Comment by WanWizard** [comment]
This requires more thought.

Currently similar behaviour is build into ORM and Model_Crud, and it should be either there or in the low-level driver, but not both. So if this is accepted, ORM and Model_Crud most be looked at, because I'm not sure that functionality can be removed without breaking existing apps.

Furthermore, you could have a lot of database definitions in your db.php, so "mis-using" a definition for something completely different is not a good idea, it should be a per-definition setting, for example:

``` php
<?php
return array(
    'db1' => array(
        'type'        => 'pdo',
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=db1',
            'username'   => 'dbuser',
            'password'   => 'dbpass',
        ),
        'identifier'   => '`',
        'table_prefix' => '',
        'charset'      => 'utf8',
        'enable_cache' => true,
        'profiling'    => false,
        'readonly'     => array('db1', 'db2'),
    ),
    'db2' => array(
        'type'        => 'pdo',
        'connection'  => array(
            'dsn'        => 'mysql:host=localhost;dbname=db2',
            'username'   => 'dbuser',
            'password'   => 'dbpass',
        ),
        'identifier'   => '`',
        'table_prefix' => '',
        'charset'      => 'utf8',
        'enable_cache' => true,
        'profiling'    => false,
    ),
);
```

@FrenkyNet, what do you think? We also need something similar in 2.0.

**Comment by hackoh** [comment]
> because I'm not sure that functionality can be removed without breaking existing apps.

Unless "enable" is set as "true", there is no influence in existing applications. 
Moreover, I think that I chose low-risk-way, after reading many codes about DB classes. 
For example, I also considered about "transactions" in the Orm Model.

Only in Database_Query_Builder_Select, connection with the slave DB is made.

**Comment by hackoh** [comment]
@WanWizard 
I changed the config format like your suggest.

**Comment by frankdejonge** [comment]
@hackoh are you on IRC right now? I'd like to discuss this.

**Comment by hackoh** [comment]
@FrenkyNet 
Sure.
But, I cannot do it not much long. 
Please let me know the information about the IRC server.

**Comment by kenjis** [comment]
#fuelphp IRC channel on freenode.

**Comment by frankdejonge** [comment]
@WanWizard FYI, Model_Crud doesn't do any replication logic I think....

**Comment by hackoh** [comment]
@kenjis 
Thank you for your information.

**Comment by WanWizard** [comment]
@kenjis Both Model_Crud and ORM support different connections for read and write, but no "load-balancing" reads over multiple slaves.

@hackoh 

What I meant is that if this will be functionality provided by the low-level driver, it should not be part of the ORM and Model_Crud code, the driver should be configured properly and it should be handled there instead of in two places. So it has to be removed from the ORM Model and Model_Crud.

**Comment by hackoh** [comment]
@WanWizard 
Did you mean about '$_write_connection' and '$_connection' right?
If some connection name specified in Model::$_write_connection (or $_connection) , It uses that preferential.
This means that the high-level layer can overwrite a setup of the low-level driver.

**Comment by hackoh** [comment]
This function operates only when DB connection name is not given.

**Comment by WanWizard** [comment]
Hmm, I'm not sure I agree with that. 

If you setup your application to use a master/slave setup for your database backend, you do that for a specific purpose, which is performance. I'm not sure the application architect would be pleased to see that carefully designed setup is not used because of alternate config at a higher level...

**Comment by kenjis** [comment]
This PR seems to be good, but I also not sure to be merged.

@hackoh 
By the way, why don't you use http://www.php.net/intro.mysqlnd-ms.php ?

**Comment by hackoh** [comment]
@kenjis 
mysqlnd is a driver of concrete more. 
Originally, DB class is not conscious of the type of RBDMS. 
The function of this PR is realized the behavior for the replication by more abstract layer.

**Comment by hackoh** [comment]
@WanWizard 
Understood.
Then, how's this?

1.
When the connection name is specified, load-balancing is carried out according to setting of 'readonly', too. 
Like a following commit.

https://github.com/hackoh/core/commit/e0a7f0d4e520a712565b0aa45d9ea87a68cd59bd

2.
Remove _write_connection from ORM and Model_Crud.

3.
Remove all codes which cares about whether the connection is writable from ORM and Model_Crud.

4.
_connection enables change of a connection place for every model. 
Since it is very useful, so it leaves this.

**Comment by WanWizard** [comment]
Thought about it. Since 1.7 is going to be the last 1.x release, 2.0 has a new database layer and will have a new ORM, I think we should leave the ORM and Model_Crud as-is, to avoid BC issues.

Can this PR be pulled as is? Lost track about with the different changes.

**Comment by hackoh** [comment]
Do you mean that I PR the branch of https://github.com/hackoh/core/commit/e0a7f0d4e520a712565b0aa45d9ea87a68cd59bd ?

**Pull request merged**
