### PR TITLE
Small fixes.

### PR DESCRIPTION
**Pull request by antitoxic**
### URI

Fixes a problem when an extension is detected in the URI and there is no slashes in the URI besides the first one. In this case `pathinfo()` will return "\" or "/" as "dirname" .
#### Example

If we load a url like `www.example.com/my-first-page.html` we expect the URI to be `/my-first-page.html` but:
- on windows it will be `\/my-first-page.html`
- on unix based platforms it will be `//my-first-page.html`
### The other change

Just adding a getter for the `Model_Crud` `$_table_name`.

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you send separate pull requests for separate issues?

This will allow us to accept them individually, now we are forced to accept them all (or none of them).

**Comment by antitoxic** [comment]
You make it a bit harder for me than needed. Is the getter a unwanted feature?

Can you point me to an explanation how can I extract a commit to a new branch painlessly?

**Comment by WanWizard** [comment]
Then you'll have to wait until someone agrees on both. I want to accept the URI fix, I don't do Model_Crud. ;)

**Comment by frankdejonge** [comment]
To add to @WanWizard's message. That's the way we manage our pull request. One feature/change per pull request. So it's not "to make it harder for you than needed", it's part of the rules we set up to maintain quality of code (and project) by keeping things organized.

**Comment by antitoxic** [comment]
:) @FrenkyNet  yes I know it's not on purpose. I'll try to do something about extracting the commit to a feature branch.

I hope it's this week at some point.

**Pull request closed without merging**
