### PR TITLE
Add DB::list_tables() for PDO_MYSQL

### PR DESCRIPTION
**Pull request by kenjis**
Related: https://github.com/fuel/core/pull/1712

### CODE REVIEW

**Comment by WanWizard** [comment]
Still very ugly, and creating a new class that extends isn't a lot of additional effort.

**Comment by Art4** [comment]
@kenjis If the method wasn't implemented for two years it seems to me, nobody needed it before. I agree with @WanWizard.

In my case #1704 I had an unique use for a list of all tables. My first thought was that someone had forgotten to implemend the method. After understanding why this isn't implemented yet I wrote a simple workaround like this one, used it and deleted it.

**Comment by WanWizard** [comment]
The main reasons nothing decent has been implemented up until now are:
- this code came from Kohana, so it takes effort to dive into it and understand it
- to do it right, DBUtil functionality needs to be moved to the driver too (as it is platform dependent code)
- don't forget the majority uses the MySQL drivers, and not the PDO ones

In case of a MySQL platform, I don't see the benefit of using PDO over MySQLi (from a framework user point of view, not from a PHP point of view), and most users will feel the same.

To address this issue, new drivers must be created, preferrably for each of the supported platforms, that start out as "extends Database_PDO_Connection" and nothing more. Then via overloading platform specific solutions can be added for list tables and columns. In a next step, custom Query drivers can be added, for example to work around the lack of support for "OFFSET" and "LIMIT". And in a final step, classes could be added to the drivers to replace the static DBUtil code.

Now, who is going to pick up this task, given the fact that the v2 database layer is already finished?

**Comment by kenjis** [comment]
Creating new classes that extend is a lot of additional effort. :-)

DB::list_tables() is the last one which is not implemented.
v1 database code is legacy, which has no tests. Nobody wants to refactor it now.

So I prefer this ad hoc solution, even if it is not clean. There are already `driver_name()` if statements in the same file.

**Comment by WanWizard** [comment]
Yes, very annoying. Because all others that didn't want to put the effort in...

**Comment by WanWizard** [comment]
Better this than nothing...

**Pull request merged**
