### PR TITLE
Changed array defaults to be compatible with 5.3

### PR DESCRIPTION
**Pull request by jpudney**
Addresses #1927

### CODE REVIEW

**Comment by emlynwest** [comment]
Line 84 of `tasks/migrate.php` also has a shorthand array usage, could you include that too please?

**Comment by WanWizard** [comment]
Line 92 as well. At least I was consistent :smirk:

**Comment by jpudney** [comment]
The other uses of `[]` are fine:

``` bash
$ php -l tasks/migrate.php
No syntax errors detected in tasks/migrate.php
$ php -v
PHP 5.3.29 (cli) (built: Jul 14 2015 16:39:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by emlynwest** [comment]
I am a little confused as `$modules = [];` should not be valid php 5.3.

**Comment by jpudney** [comment]
@stevewest indeed, where are you seeing that? I've search through the core but can't find it…

**Comment by emlynwest** [comment]
Sorry, my mistake. The code in the diff you linked in #1927 has since been changed.

**Comment by jpudney** [comment]
I see now :smiley:!

**Pull request merged**
