### PR TITLE
Precision fix for Image_Driver

### PR DESCRIPTION
**Pull request by dudeami0**
Fixed an error where floats precision loss adversely affected outputted image. Known to happen when resizing image under ~2% of original size.

### CODE REVIEW

**Comment by nerdsrescueme** [comment]
Awesome. I was going off the main page where it says it needs to be installed. Sweet man. I can actually use this in a project I have coming up.

**Comment by nerdsrescueme** [comment]
http://www.php.net/manual/en/bc.installation.php I guess it depends on whether enough default installations have enabled it? Hopefully it goes in, that way I don't need to worry about it for my photo editor project. That would be lovely.

**Comment by dudeami0** [comment]
If it becomes a problem, I'll most likely check for BCMath support or make it a config option

**Comment by jschreuder** [comment]
Good work on making BCMath optional, but you're not entirely up to the coding standards: all brackets must be on their own line.

**Pull request merged**
