### PR TITLE
Fixed Autoloader::load() function + Config::save() to work with modules

### PR DESCRIPTION
**Pull request by axelitus**

### CODE REVIEW

**Comment by WanWizard** [comment]
As been discussed at issue #84, testing for a backslash to determine the module is a bad idea on Windows systems, where the backslash is the default DIRECTORY_SEPARATOR (DS).

As said there, we need to think about a different way of defining the module, or have it fall through if no module namespace can be found.

**Comment by axelitus** [comment]
[In this post](http://fuelphp.com/forums/posts/view_reply/1402) I propose using a pipe to define a namespace/module

Despite of this still pending issue, the Autoloader did a strtolower() to the namespace, which it is not done anywhere else; so if the find_file() issue is fixed in the future, this still needs to be fixed...

**Comment by WanWizard** [comment]
I have decided to opt for fall-through. If backslash detection doesn't lead to a valid namespace, the file will be looked for in the global namespace.

**Comment by WanWizard** [comment]
Wasn't happy with the fall-through, as it would make folders with the same name as a defined namespace unaccessable (since the namespace path would always be selected).

You now have to use the double colon to access a file in a namespace ('module::folder/file').

**Comment by axelitus** [comment]
I get error:

```
ErrorException [ Warning ]: pathinfo() expects parameter 1 to be string, array given

COREPATH/classes/config.php @ line 124:

123:
124:    $path = pathinfo($path);
125:
```

**Comment by axelitus** [comment]
<del>I put:
    else
    {
        $path = $path[0];
    }
after [Line 113](https://github.com/fuel/core/blob/develop/classes/config.php#L113) in the config.php file</del> Don't do this... it's not a real solution... instead read ahead...

**Comment by axelitus** [comment]
Ok did some more digging and found out that the 'problem' is that when the path is cached it is returned as an array from the [line 285](https://github.com/fuel/core/blob/develop/classes/fuel.php#L285):

```
return static::$path_cache[$cache_id.$path];
```

in the find_file() function. Shouldn't it be:

```
return static::$path_cache[$cache_id.$path][0];
```

or look for the $multiple param?

**Comment by WanWizard** [comment]
find_file() should maintain a different cache for single and multiple file requests. I've just committed a fix.

**Comment by axelitus** [comment]
Fine, I'll check it tomorrow... that should do I think, but I'll do some testing tomorrow...

I'm not sure that will be enough... I'm not decided yet hehe

**Comment by axelitus** [comment]
The last commit breaks again...

I get the "Fatal error: Exception thrown without a stack frame in Unknown on line 0" message...

I've already downloaded a clean copy of the develop branch to make sure it wasn't some code of mine. I'll dig into it to see what's happening...

**Comment by axelitus** [comment]
Found it!
As $cache_id is initialized either with 'M.' or 'S.', on [line 261](https://github.com/dudeami/core/blob/75966039beb6926e43bc4a957323c2789028073e/classes/fuel.php#L261) we cannot check for an empty $cache_id as it won't be empty.

I changed it for

```
if (strlen($cache_id) == 2)
```

and everything is working again... well, at least it shows me the Exception page. I'll keep testing...

**Comment by jschreuder** [comment]
I just changed it to `if (empty($paths))` should work fine, @WanWizard can you check this?

**Comment by axelitus** [comment]
That would work except for the absolute path part which doesn't modify the $paths array, only the $cache_id...
it could be `if(empty($paths) && empty($found))` though...

**Comment by WanWizard** [comment]
decided to revert some of the changes, and only add the multiple/single cache identifier at the end.

**Comment by axelitus** [comment]
Seems to be working alright... and it's just a much cleaner solution!

**Comment by WanWizard** [comment]
Ok, thanks for the feedback.

**Comment by axelitus** [comment]
Thank you for the hard work you're all doing and the fantastic framework you're building...

I think we can consider this issue as closed now after all headaches it gave... :)

**Pull request closed without merging**
