### PR TITLE
Add in_transaction method. classes/db.php

### PR DESCRIPTION
**Pull request by srea**
Hello  
I add "in_transaction" method in db.php, because very useful.  
Thank you.

### CODE REVIEW

**Comment by frankdejonge** [comment]
Looks good, can you add docs for this? Then I'll merge the pull.

**Comment by srea** [comment]
ok  I add docs now. thank you

**Comment by srea** [comment]
I added docs for this.
https://github.com/fuel/docs/pull/383

**Comment by srea** [comment]
thank you for merge

**Pull request merged**
