### PR TITLE
Update router.php

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you explain why you feel this is needed? What use case does this address? Can you give a code example?

**Comment by JefferyHus** [comment]
a commit without explanation is nothing honestly, please explain your case, as it may work for you but not the rest.

**Comment by ghost** [comment]
@WanWizard @JefferyHus Why in the foreach loop many times declare the $ replace variable? I think that this will be better.

**Comment by JefferyHus** [comment]
if the `$replace` is affected in the first condition inside `foreach` it will remain with the same value in the next loop, so if the first condition isn't fired in the second loop there will be an issue as the second route even without params it will execute it with the previous `$replace` value, therefor you should refresh the value each time you loop.

**Pull request closed without merging**
