### PR TITLE
Removed $_properties from model/crud.php

### PR DESCRIPTION
**Pull request by arbme**
Removed $_properties as its not used with model/crud.php as far as I can see.

### CODE REVIEW

**Comment by jschreuder** [comment]
You are removing the very point where it is used:

``` php
<?php
if (isset(static::$_properties))
{
    $vars = \Arr::filter_keys($vars, static::$_properties);
}
```

This filters the variables that are saved by the properties that are set, all others are ignored.

**Comment by arbme** [comment]
I understand the concept but in the docs for model crud under configuration, it has no mention of $_properties so dont see why it is needed. Does ORM use this class?

**Comment by jschreuder** [comment]
It removes properties that are set on the model but you don't want in the database. This allows you to set additional properties that aren't DB data. And read what I said as I pretty much explained this in my previous post.

This has nothing to do with the ORM and that something isn't in docs doesn't mean anything, especially when it's usefull functionality. All it might mean is that someone added this without documenting it.

**Comment by arbme** [comment]
Thanks you for the explaination

**Comment by frankdejonge** [comment]
Just for the record, the docs where updated right after this push.

**Pull request closed without merging**
