### PR TITLE
added Input::param_valid($key, $array)

### PR DESCRIPTION
**Pull request by younes0**
Taken from Flourish:
http://flourishlib.com/docs/fRequest#RestrictingValidValues

The method param_valid() simplifies the process a great deal by taking
exactly two parameters, $key, the key to request the value for and
$valid_values, an array of permissible values. If the value is not one
of the valid value, the first valid value will be picked. Here is an
example:

<?php
// $action will get the value 'list' if no value was present
$action = Input::param_valid('action', array('list', 'search'));
?>

### CODE REVIEW

**Comment by tomschlick** [comment]
Whats the use case for it just picking the first $valid_value if the key does not exist? I would think if the key does not exist it should just return false because it could not find a valid value.

**Comment by frankdejonge** [comment]
I can see a usecase for this. Sort of like an enum restriction, but then in code. I just don't think this is the right implementation and naming of such a feature, nor am I sure this really has a place in the core. And if it was implemented I'd like to see a restriction on which input array is fetched from. Any thoughts @WanWizard @jschreuder @philsturgeon @dhorrigan ?

**Comment by younes0** [comment]
It might be not have its place in the core but it should be added to Fuel since it's a very common usecase.

```
 Class Controller_Inbox{
      public function action_index() 
      {
           $status  = Input::param_valid('status', array('all', 'unread', 'unresponded', 'hidden'));
           $orderby = Input::param_valid('orderby', array('datetime', 'name'));
           $rpp = Input::param_valid('rpp', array(10, 50, 100)); // results per page
      }
 }
```

if no get parameters : default values are set: status=all, orderby=datetime, rpp=10
if rpp is equal to 10000 which is not a whitelisted value, then the default value is set (10)

**Comment by WanWizard** [comment]
In my opinion it's very application specific. 

Input should not concern itself with parameter validation, and given the fact that you'd have to define everything in the controller anyway it's easily replaced by

```
$status = Input::param('status', false);
$status = in_array($status, array('all', 'unread', 'unresponded', 'hidden')) ? $status : 'all';
```

Or by a helper method that does this. I can understand the use case, but that is by far not restricted to Input parameters. I can come up with lots of scenario's where you would want to do something like this, not related to Input.

So in this state -1.

**Comment by tomschlick** [comment]
@FrenkyNet oh i definitely can see a use case for it, i would just rather the developer provide a $default like we do in Arr::get instead of just picking the first item.

**Comment by younes0** [comment]
Okay I understand, thanks for your explanations, I'll close the pull then.

**Comment by tomschlick** [comment]
basically

``` php

public static function param_valid($key, $valid_values, $default = null)
{
    settype($valid_values, 'array');
    $valid_values = array_merge(array_unique($valid_values));
    $value = static::param($key);
    if (!in_array($value, $valid_values)) 
    {
        return $default;
    }
    return $value;
}

```

**Comment by tomschlick** [comment]
Also I dont think this whole line is needed as it wouldn't matter if a whitelisted param was in the allowed multiple times as this method is just checking for the existence of it.

``` php
$valid_values = array_merge(array_unique($valid_values));
```

**Comment by philsturgeon** [comment]
-1

Emailing from my iPhone 4S like a BOSS!

**Pull request closed without merging**
