### PR TITLE
Ability to stick the profiler (PQP_SHOWONLOAD)

### PR DESCRIPTION
**Pull request by filisko**
Hi,
So I just added the ability to stick the profiler (PQP_SHOWONLOAD) dynamically using a cookie, have a look!

Regards,
Filis.

### CODE REVIEW

**Comment by filisko** [comment]
Woops, I will send another one in few minutes.

**Comment by filisko** [comment]
Now is ok :+1:

**Comment by WanWizard** [comment]
I am not sure having something client side trigger this is a good idea, it may be abused and expose a lot of internal information.

**Comment by filisko** [comment]
how do other debug bars do it?

**Comment by WanWizard** [comment]
What exactly do you want to archieve? Personally, I find it a bit pointless to have the profiler fill the entire screen on every page load, obscuring the page, only so you don't have to click the "show" link.

**Comment by filisko** [comment]
It's only a toggle for PQP_SHOWONLOAD, so you could enable it and disable it without touching code.

**Comment by WanWizard** [comment]
I got that, but I never understood why one would always want to do that. You look at the profiler when you need to, by clicking the link. Why do you need it to obscure your app output on EVERY page load?

**Comment by filisko** [comment]
If you want to compare a lot of pages in a couple of seconds, it's faster than going to the page and having to open it every time. But hey, you're also right. And you can achieve this by putting some javascript there, which is nice.

**Pull request closed without merging**
