### PR TITLE
Fatal error when running oil test

### PR DESCRIPTION
**Pull request by tarnfeld**
PHP Fatal error:  Call to a member function get() on a non-object in /sites/twtmore/fuel/core/classes/uri.php on line 167

### CODE REVIEW

**Comment by dhrrgn** [comment]
These should return `null` instead of `false`.

**Comment by dhrrgn** [comment]
Good catch tho.

**Comment by tarnfeld** [comment]
Sure, will fix. I use tests a lot, no code goes live until the tests pass so i'm fixing all the things that cause tests to fail in the core now... have you seen the state of the num.php test :S :/

**Comment by dhrrgn** [comment]
Haha, ya.  Someone had those in their pull request.  Haven't had time to go through it properly.

**Pull request closed without merging**
