### PR TITLE
Propose \Arr::sum()

### PR DESCRIPTION
**Pull request by hackoh**
This addition is a  simple shortcut of
`array_sum($array)` and `array_sum(\Arr::pluck($array, 'key.to.value'))`

### CODE REVIEW

**Comment by tomschlick** [comment]
Seems like a pretty good addition to me :+1:

Writing the docs pull request for this ahead of time will probably help get it accepted quicker.

**Comment by hackoh** [comment]
@tomschlick 
OK, thanks.
I'll PR to docs.

**Comment by WanWizard** [comment]
@FrenkyNet ok for you?

**Comment by frankdejonge** [comment]
I'd say the second param should be required, there is no need to make an alias for array_sum and this does something different, therefor I'd suggest a pluck and then a array_sum on the result, no recursive strategy. @WanWizard agree?

**Comment by hackoh** [comment]
If FrenkyNet's opinion is adopted, there is a ready to fix the code and docs.
And, I'll change the Arr::average() by other branch.

**Comment by WanWizard** [comment]
@FrenkyNet agree.

**Comment by hackoh** [comment]
Ok. I just prepare to PR.

**Comment by hackoh** [comment]
Ah, no no, prepare to fix..

**Comment by frankdejonge** [comment]
@hackoh you've got a merge-conflict, so I can't merge it. Can you resolve this?

**Comment by WanWizard** [comment]
Corrected and commited.

**Pull request closed without merging**
