### PR TITLE
years should be singular year.

### PR DESCRIPTION
**Pull request by jyggen**

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you send a pull request for the documentation too so we can keep everything in sync?

**Comment by jyggen** [comment]
What do you mean?

**Comment by WanWizard** [comment]
The class documentation also mentions 'years' instead of 'year'. 

By accepting this pull request without the corresponding documentation changes, the code will no longer be in sync with the docs.

**Comment by jyggen** [comment]
Done: https://github.com/fuel/docs/pull/327

**Comment by WanWizard** [comment]
Great, thanks.

**Comment by WanWizard** [comment]
( note to github: don't put the close button under by mouse pointer please... ;-)

**Pull request merged**
