### PR TITLE
add before_view() method to ViewModel

### PR DESCRIPTION
**Pull request by takyam-git**
The `ViewModel::before()` method excuted on `ViewModel::forge()`.  
`before()` can't get params of set after forge.

``` php
example: <?php
//on controller
$this->template->content = ViewModel::forge('foo/bar');
$this->template->content->set('param_a', $param_a);

//on class View_Foo_Bar
public function before()
{
    Debug::dump($this->param_a); // OutOfBoundsException [ Error ]: View variable is not set:param_a
}
```

The `before_view()` method can do it.

### CODE REVIEW

**Comment by WanWizard** [comment]
Isn't the actual problem here that the before() is called in the Viewmodel constructor, instead of before rendering the view? It seems more logical to me to move the before() call...

**Comment by takyam-git** [comment]
Yes, I think that too, but I feel uneasiness of backward compatibility.
If there's no problem move `before()`, then I want to do it.

**Comment by WanWizard** [comment]
I don't see an immediate issue, so if you can move it, please do.

**Comment by takyam-git** [comment]
I sent new pull request #1412,  please see it.

**Pull request closed without merging**
