### PR TITLE
Fix Arr::get \ArrayAccess bug

### PR DESCRIPTION
**Pull request by tomschlick**
Fixes a case where you cant access an \ArrayAccess object's data through Arr::get() because of a bug in array_key_exists

### CODE REVIEW

**Comment by tomschlick** [comment]
btw unit tests ran clean

**Comment by WanWizard** [comment]
This is an issue with all code that accepts an array(), and uses one of the array_... functions, as none support ArrayAccess.

@dhorrigan: any rules on what will get a workaround, and what not (trying to avoid non-consistent behaviour)?

**Comment by dhrrgn** [comment]
Can't believe we didn't catch this before.  Anywhere we allow ArrayAccess should get a similar fix I suppose.

@tomschlick You have code formatting issues. `if( ($array instanceof \ArrayAccess and isset($array[$key_part])) === false )`  should be `if (($array instanceof \ArrayAccess and isset($array[$key_part])) === false)`.

**Comment by WanWizard** [comment]
You mean anywhere we allow an array as argument? Hmm... Going to be a long night then...

**Comment by dhrrgn** [comment]
No, just anywhere that we explicitly allow ArrayAccess.  I dont think it is many places really...I think a lot of time we have compensated for this (I know we do in the Security class).

**Comment by WanWizard** [comment]
Which is nowhere. There are only a few classes that explicitly allow ArrayAccess, and none of them use array_ functions on the argument passed as far as I can see.

**Pull request merged**
