### PR TITLE
Made configurable first/last, next/previous markers

### PR DESCRIPTION
**Pull request by SCIF**
Pagination class didn't can to configure text of first/last and next/previous links. Fixed it.
Added new template values: first-marker, previous-marker, next-marker, last-marker.

### CODE REVIEW

**Comment by WanWizard** [comment]
Why only add it to the bootstrap template, and not to the default template? And can you also update the pagination docs?

**Comment by SCIF** [comment]
Ok. I will do request with default and bootstrap templates :) Also if it's good idea — i will update docs.

**Comment by WanWizard** [comment]
And I think it will be a good idea to use HTML entities (&raquo;) instead of the characters themselfs.

**Comment by SCIF** [comment]
Don't know how to attach patch to existence pull request. Therefore — #1336

**Comment by WanWizard** [comment]
#1336 got merged.

**Pull request closed without merging**
