### PR TITLE
Added Mongo_Db::get_one() to obtain only one document.

### PR DESCRIPTION
**Pull request by ipalaus**
I have added `Mongo_Db::get_one()` that uses `MongoCollection::findOne` just for performance reasons: findOne is faster than find with a limit of 1.

I have done tests of 10.000 executions and that is what I've:

> Excuted in 1.0861890316 seconds, with an average of 0.00010861890316 sec/each
> Excuted in 1.19088315964 seconds, with an average of 0.000119088315964 sec/each

### CODE REVIEW

**Comment by ipalaus** [comment]
http://www.mongodb.org/pages/viewpage.action?pageId=1475411#PerformanceTesting-FindOne%2CNoIndex

find_one (small, no index) - 989
find (small, no index)  - 554

**Comment by WanWizard** [comment]
@philsturgeon: care to check this out?

**Comment by philsturgeon** [comment]
Agreed, this is pretty useful as findOne() does not have to deal with collection returns and all that jazz.

@ipalaus: Can you add this to documentation then reference the link in here and I'll approve them both.

**Comment by tomschlick** [comment]
Added the documentation here https://github.com/fuel/docs/pull/265

**Comment by ipalaus** [comment]
@philsturgeon @tomschlick thank you!

**Comment by tomschlick** [comment]
no problem. i needed it for the Mongo_Crud class I'm working with!

**Comment by ipalaus** [comment]
@tomschlick can we chat on #fuelphp @ freenode? I'm also doing a Mongo CRUD class

**Pull request merged**
