### PR TITLE
\DB::count_last_query() should be static, allows to use \DB::count_last_query()

### PR DESCRIPTION
**Pull request by crynobone**
As per comment https://github.com/fuel/core/commit/fcd27c1724c1d08e0df293f90ad4a7b7fdd2201d#commitcomment-640297

### CODE REVIEW

**Comment by kriansa** [comment]
Just like I did in my pull request a few days ago...  3bd6ccbc18f7f0efcfb6b4422737b5517582ca16

**Comment by crynobone** [comment]
Someone need to merge this soon...

**Comment by kriansa** [comment]
I think you missclicked and closed the pull request...

**Comment by crynobone** [comment]
I pull request would be enough :)

**Comment by crynobone** [comment]
I can't find your changeset in 1.1/develop tree.. Reopening this

**Pull request merged**
