### PR TITLE
Fix csrf_autoload bug. It be check only 'POST', 'PUT' and 'DELETE' http methods.

### PR DESCRIPTION
**Pull request by takyam-git**
Currently check allmethod on csrf_autoload is true.  
It will be catch \SecurityException when I access to some pages by http GET method.

this pull request check http methods and run check_token() only post, put and delete method.

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you add this to the docs too?

**Comment by takyam-git** [comment]
I send pull request to fuel/docs now.
https://github.com/fuel/docs/pull/514

**Comment by WanWizard** [comment]
This can no longer be merged as it conflicts with your other change. I've added it manually.

**Comment by takyam-git** [comment]
thanks!

**Comment by WanWizard** [comment]
I've made generate_token() general (not related to csrf) and public, as it can be used in other situations where you need a random token.

**Pull request closed without merging**
