### PR TITLE
Stylefixes

### PR DESCRIPTION
**Pull request by it-can**
Fixed a lot of code styling with this command:

```
php-cs-fixer fix . --fixers=linefeed,eof_ending,encoding,function_call_space,line_after_namespace,php_closing_tag,trailing_spaces,extra_empty_lines,include,multiline_array_trailing_comma,namespace_no_leading_whitespace,no_blank_lines_after_class_opening,double_arrow_multiline_whitespaces,elseif,method_argument_space,spaces_cast,ternary_spaces --verbose
```

### CODE REVIEW

**Comment by huglester** [comment]
Thanks

**Comment by emlynwest** [comment]
Looks good, thanks!

**Comment by WanWizard** [comment]
Thanks. Can that also find if's without braces?

**Comment by it-can** [comment]
@WanWizard oooh good question... I'll take a look

**Comment by it-can** [comment]
@WanWizard php-cs-fixer doesn't seem to have this option... The missing braces is not only for `if` statements but also for `foreach` `for` etc...

**Comment by WanWizard** [comment]
Was afraid of that. Sounds like a lot of manually work is needed to find all of them. Personally I don't expect `for` and `foreach` without braces, but I saw some `if`'s when going through the changes for this PR...

**Comment by kenjis** [comment]
@WanWizard It was not hard work. I sent a PR to fix them.

**Pull request merged**
