### PR TITLE
Fixed a weird is_scalar conflict

### PR DESCRIPTION
**Pull request by tomschlick**
In some cases if $checked = false but is boolean and the value of the
field is '0' the is_scalar would evaluate to true which obviously shouldn't happen.
making the statement two if clauses fixes this because it wont drop down into the
is_scalar block

### CODE REVIEW

**Comment by WanWizard** [comment]
This is odd, both statements are identical?

**Comment by tomschlick** [comment]
No because in the first if the $checked is boolean but not === true it will then go to the elseif which could evaluate to true if the value of the field is something that is_scalar picks up on. 

In my change if its bool but not checked it just doesn't add anything which should be the proper behavior.

**Comment by WanWizard** [comment]
Ah, missed the elseif, wasn't visible in the diff. That indeed changes things.

**Comment by tomschlick** [comment]
Thanks!

**Pull request merged**
