### PR TITLE
Microsoft SQL Server Driver added

### PR DESCRIPTION
**Pull request by cocteau666**
For using Microsoft Azure and Windows with FuelPHP, I request to merge this driver.
This driver use a native driver for SQL Server (php_sqlsrv.dll). 

System Requirements.
OS : Windows Server 2008 or higher (Include Microsoft Azure Web Apps)
Database: Microsoft SQL Server 2008 or higher (Include Microsoft Azure SQL Database)
SQL Server Driver:  php_sqlsrv.dll

### CODE REVIEW

**Comment by WanWizard** [comment]
Does that fully support all DB methods, like limit and offset which used to be the problem? 

If so, thank you very much for your contribution, making FuelPHP even more awesome!

**Comment by cocteau666** [comment]
Exactly.

Now I can not decide how to write classes in "core/classes/database/query/builder/".
Using "if $config['type'] === 'sqlsrv' " is easy way, but it's not excellent.

**Comment by cocteau666** [comment]
I tried to support "LIMIT ... OFFSET" query for SQL Server.

**Comment by atabak** [comment]
cocteau666 can you please send me complete fuel file for SQL Server

**Pull request closed without merging**
