### PR TITLE
Reusing one memcached connection

### PR DESCRIPTION
**Pull request by tomschlick**
instead of making 1 connection per Cache::get/set/delete call this saves the
memcached connection as a static variable to avoid DOSing your memcached
server if you have many cache calls on the same page

### CODE REVIEW

**Comment by dmyers** [comment]
I'm kind of surprised `Cache` doesn't have an `instance()` method and work off that as I would imagine this would affect the other cache storage classes as well.

**Comment by WanWizard** [comment]
The best solution (for the future) would be to separate the two, and have specific backend storage drivers, like you have with DB (where indeed a common instance is shared amongst everything using that backend).

**Comment by WanWizard** [comment]
@tomschlick can you do the same for Redis?

**Comment by tomschlick** [comment]
Updated Redis to do the same.

**Comment by WanWizard** [comment]
Thanks!

**Pull request merged**
