### PR TITLE
Add the template options to next_link and previous_link method

### PR DESCRIPTION
**Pull request by faabiosr**
Including next_start and next_end to next_link function.
Including previous_start and previous_end to prev_link function.

### CODE REVIEW

**Comment by notrab** [comment]
I'm currently having this issue and would love the ability to set template options for the previous/next links without having to use an ExtendedPagination Class.

**Comment by faabiosr** [comment]
Me too, but the previous/next link option is not implemented. The options are defined in code, but don't work.

**Comment by jschreuder** [comment]
The pagination class as it currently exists will be replaced (#601), thus we do not accept any pull-requests on it anymore.

**Comment by faabiosr** [comment]
OK, no problem.

**Pull request closed without merging**
