### PR TITLE
Added the methods collection() and set() for easy usage of Mongo_Db

### PR DESCRIPTION
**Pull request by ipalaus**
Hello,

I have modified the Mongo_Db class and added collection() and set() methods to has it as an optional usage. So we can do something like:

`Mongo_Db::instance()->collection('users')->set(array('name' => 'Isern', 'surname' => 'Palaus'))->insert();`

This will help @tomschlick and me with the development of Mongo_Crud: https://github.com/tomschlick/fuel-mongo-crud and in general to all Mongo_Db users.

Please, @philsturgeon tell us what do you think about.

Thank you!

### CODE REVIEW

**Comment by alexbilbie** [comment]
There are a whole load of functions (including `set()`) in my CodeIgniter library which I've added since I created the Fuel library:

https://github.com/alexbilbie/codeigniter-mongodb-library/blob/master/README.md

I'm hoping that on Friday I'll get an opportunity to work on the next version of the library that will be framework agnostic and merge best practises of both versions.

**Comment by philsturgeon** [comment]
Alex, shall i leave this and wait for yours?

**Comment by alexbilbie** [comment]
@philsturgeon ta

**Comment by philsturgeon** [comment]
Sorry buddy, we have a bigger plan.

**Comment by ipalaus** [comment]
hey @alexbilbie, any update about this? thank u!

**Comment by ipalaus** [comment]
@alexbilbie @philsturgeon any news on this? thank you in advance!

**Comment by nedmas** [comment]
Hey @ipalaus @alexbilbie @philsturgeon just to add my two cents, it would be really useful to have some more info on the plan for mongo in fuel. Even if it's 'There is nothing in the pipeline in the short term'. Thanks

**Comment by alexbilbie** [comment]
I'm working away (with @jacksonj04) on v2 of my original CodeIgniter library - https://github.com/alexbilbie/codeigniter-mongodb-library/tree/v2 - from which the Fuel version was based on. As soon as it is ready (and it includes the changes mentioned in this ticket) it will be ported back to Fuel.

**Comment by tomschlick** [comment]
@alexbilbie nice dude. I have a bunch of tweaks I've made to my mongo libs over the past year or so... i'll submit a pull request if I get the time on your repo and hopefully they will eventually make it back into fuel core.

**Pull request closed without merging**
