### PR TITLE
Model_Crud::count() bug fix

### PR DESCRIPTION
**Pull request by Onuma0519**
http://fuelphp.jp/docs/1.7/classes/model_crud/methods.html#/method_count
where is error.

### CODE REVIEW

**Comment by emlynwest** [comment]
What exactly is the problem that this "fixes"?

**Comment by Onuma0519** [comment]
In the same code as the document, it is an error.

$nbr_of_records = Model_User::count('id', true, array('group', '=', 100));
↓
This is can run successfully
$nbr_of_records = Model_User::count('id', true, array(array('group', '=', 100)));

**Comment by emlynwest** [comment]
@WanWizard Model_Crud is more your area, thoughts?

**Comment by WanWizard** [comment]
Who? Me? Never used it. :-)

Looking at the purpose and the code, I'd say the docs are incorrect. You would need this code to be able to do:

```
$nbr_of_records = Model_User::count(
    'id', 
    true, 
    array(array('group', '=', 100),array('field', '=', 'value'))
);
```

**Comment by emlynwest** [comment]
Indeed does seem to be the docs then, so this PR can be closed.

**Pull request closed without merging**
