### PR TITLE
Added encoding based on content type for cUrl requests

### PR DESCRIPTION
**Pull request by nedmas**
I needed to send a cUrl PUT request with an XML payload, so I wrote an encode method to check the content type and use the Format class to encode the data.

### CODE REVIEW

**Comment by philsturgeon** [comment]
This is very close to what I have in mind but not quit. By using "supported_formats" you are making `application/json` work but not `text/json` for example.

You should really be using the `static::$auto_detect_formats` array which is designed for this sort of thing, but it means you will need to rejig the code somewhat.

**Comment by nedmas** [comment]
Thanks for the pointer Phil, I completely missed that. I'll get on and change the code and update the request.

**Comment by nedmas** [comment]
@philsturgeon is this closer to what you had in mind?

**Comment by philsturgeon** [comment]
Magic!

**Comment by philsturgeon** [comment]
As an afterthought, while this is helpful for curl, if this can be moved into the driver logic more that would be very handy, as of course HTTP Stream wrapper driver for example would also need similar logic.

**Pull request merged**
