### PR TITLE
Propose Arr::search()

### PR DESCRIPTION
**Pull request by hackoh**
I encountered the case where Arr::search() was needed.
Would you check?

### CODE REVIEW

**Comment by hackoh** [comment]
If this PR is adopted, I am ready to PR to docs.

**Comment by WanWizard** [comment]
PR is ok. If you can create the PR for the docs, I'll merge them both.

**Comment by WanWizard** [comment]
Thanks!

**Comment by frankdejonge** [comment]
@WanWizard I'd be in favor of defaulting the recursive param to `true` it's because of recursion that this is handy, therefor defaulting makes sense. Agree?

**Comment by WanWizard** [comment]
Agreed. Makes much more sense.

**Pull request merged**
