### PR TITLE
Log Enhancements

### PR DESCRIPTION
**Pull request by dbpolito**
Related to https://github.com/fuel/core/pull/1126

I think that would be a great addition to the framework some enhancements to log:
1. Changes Log to be Driver-Based
   - Makes possible to have logs stored on file or database simply changing on config (similar to session).
2. Makes easier to understand custom levels.
3. Creates an Event (log_called for example) so we can easily use that for example to send an e-mail if we get error log.

**Important Note:** This change will not make any application crash, only will be need a heads up about configuration because it moves from config.php to a log.php file.

This is an initial commit so i can get feedback and see if it's getting good.

Still pending:
1. Makes an Oil Task for create the logs table as we have on session.
2. Change Docs

Let me know your thoughts.

### CODE REVIEW

**Comment by dbpolito** [comment]
Working on Docs and Oil Task, i'm going to pull it very soon.

**Comment by WanWizard** [comment]
If the levels are no longer a constant, then perhaps something needs to happen to the static methods currently being used (I might not have a level called 'warning', and I might have a level called 'something' for which no method exists).

Perhaps they can be replaced by a __callStatic() that checks the existance of the level?

**Comment by WanWizard** [comment]
@dbpolito I'm planning a 1.4 release, do you think you can wrap this up in the next few days?

**Comment by dbpolito** [comment]
@WanWizard Yes i can... I think until monday i get this done... loved the __callStatic idea, I'm implementing it too.

**Comment by WanWizard** [comment]
Cool, thanks. I'll plan the 1.4 release for sometime next week.

**Comment by WanWizard** [comment]
We had a short discussion about this within the team. We might switch to monolog as our logging backend when we have integrated composer support. 

Nothing has been decided yet, but given this I don't think we should include this change in 1.4.

**Comment by tomschlick** [comment]
Monolog would be a great option but are there plans for composer by default in 1.x? or just 2.0?

**Comment by WanWizard** [comment]
There are plans to add composer to 1.5, as one of the steps to "ease" the transition to a new architecture.

**Comment by tomschlick** [comment]
Awesome.

**Comment by dbpolito** [comment]
@WanWizard So it's not going to be merged right? Should we close this one? If you change your mind, i can finish that up.

**Comment by WanWizard** [comment]
It's entirely up to you. Current plan is to introduce Monolog in 1.5 or 1.6.

**Comment by dbpolito** [comment]
Thinking about this if the plan is moving to Monolog i don't think it's a good idea implement this, it's going to change the same thing in a small portion of time.

I can do it if you want but i don't think it's going to worth it.

Let me know your thoughts.

**Comment by dbpolito** [comment]
@WanWizard Thoughts?

**Comment by WanWizard** [comment]
Monolog will be introduced in 1.5, so I'll close this.

**Pull request closed without merging**
